import type { StockRiskAssessmentInput, StockRiskAssessmentItem, StockRiskSeverity } from '../../types/stockRiskAssessment'

const severityRank: Record<StockRiskSeverity, number> = { high: 3, medium: 2, low: 1 }

export function assessStockRisks(input: StockRiskAssessmentInput): StockRiskAssessmentItem[] {
  const risks: StockRiskAssessmentItem[] = []
  const add = (risk: Omit<StockRiskAssessmentItem, 'formulaVersion' | 'tradeDate'>) => risks.push({ ...risk, formulaVersion: 'stock-risk-v1.0', tradeDate: input.tradeDate })
  if (input.rsi14 !== null && input.rsi14 >= 75) add({ id: 'rsi-overheated', title: 'RSI 短線偏熱', severity: input.rsi14 >= 82 ? 'high' : 'medium', category: 'momentum', explanation: 'RSI 位於高檔區，短線波動可能放大。', evidence: { rsi14: input.rsi14, threshold: 75 }, source: 'GULI Derived from TWSE Official History' })
  if (input.k !== null && input.d !== null && input.k < input.d && input.k >= 75) add({ id: 'kd-turning', title: 'KD 高檔轉弱', severity: 'medium', category: 'momentum', explanation: 'K 值在高檔低於 D 值，動能出現轉弱訊號。', evidence: { k: input.k, d: input.d }, source: 'GULI Derived from TWSE Official History' })
  const atrPercent = input.atr14 !== null && input.close ? input.atr14 / input.close * 100 : null
  if (atrPercent !== null && atrPercent >= 4) add({ id: 'atr-high', title: 'ATR 波動偏高', severity: atrPercent >= 6 ? 'high' : 'medium', category: 'volatility', explanation: 'ATR 相對股價偏高，單日價格區間可能較大。', evidence: { atrPercent: Number(atrPercent.toFixed(2)), threshold: 4 }, source: 'GULI Derived from TWSE Official History' })
  if (input.volatility20 !== null && input.volatility20 >= 35) add({ id: 'volatility-high', title: '年化波動率偏高', severity: input.volatility20 >= 50 ? 'high' : 'medium', category: 'volatility', explanation: '近 20 日年化波動率高於固定風險門檻。', evidence: { volatility20: input.volatility20, threshold: 35 }, source: 'GULI Derived from TWSE Official History' })
  if (input.volumeRatio !== null && input.volumeRatio >= 2.2) add({ id: 'abnormal-volume', title: '成交量明顯放大', severity: input.volumeRatio >= 3 ? 'high' : 'medium', category: 'volume', explanation: '成交量明顯高於 20 日均量，需搭配價格方向解讀。', evidence: { volumeRatio: input.volumeRatio, threshold: 2.2 }, source: 'GULI Derived from TWSE Official History' })
  if (input.volumeRatio !== null && input.volumeRatio < 0.55) add({ id: 'low-volume', title: '量能偏低', severity: 'medium', category: 'volume', explanation: '成交量低於 20 日均量 55%，趨勢延續性需再確認。', evidence: { volumeRatio: input.volumeRatio, threshold: 0.55 }, source: 'GULI Derived from TWSE Official History' })
  if (input.nearestResistanceDistancePercent !== null && input.nearestResistanceDistancePercent <= 2) add({ id: 'near-resistance', title: '接近壓力區', severity: 'medium', category: 'price-structure', explanation: '現價距最近壓力區不超過 2%。', evidence: { distancePercent: input.nearestResistanceDistancePercent, threshold: 2 }, source: 'support-resistance-v1.0' })
  if (input.close !== null && input.ma20 !== null && input.close < input.ma20) add({ id: 'below-ma20', title: '低於 MA20', severity: 'medium', category: 'price-structure', explanation: '收盤價低於 20 日均線，中期趨勢承壓。', evidence: { close: input.close, ma20: input.ma20 }, source: 'GULI Derived from TWSE Official History' })
  if (input.close !== null && input.ma60 !== null && input.close < input.ma60) add({ id: 'below-ma60', title: '低於 MA60', severity: 'high', category: 'price-structure', explanation: '收盤價低於 60 日均線，波段結構偏弱。', evidence: { close: input.close, ma60: input.ma60 }, source: 'GULI Derived from TWSE Official History' })
  if (input.institutionalNetShares !== null && input.institutionalNetShares < 0) add({ id: 'institutional-sell', title: '法人單日賣超', severity: 'medium', category: 'institutional', explanation: '三大法人官方單日合計為賣超；單日資料不代表連續趨勢。', evidence: { netShares: input.institutionalNetShares }, source: 'TWSE Official Institutional' })
  if (input.industryStrength !== null && input.industryStrength < 45) add({ id: 'industry-weak', title: '產業相對偏弱', severity: 'medium', category: 'industry', explanation: '產業強度低於固定觀察門檻。', evidence: { industryStrength: input.industryStrength, threshold: 45 }, source: 'GULI Industry Snapshot' })
  if (input.decisionScore !== null && input.technicalScore !== null && Math.abs(input.decisionScore - input.technicalScore) >= 20) add({ id: 'score-mismatch', title: '決策與技術分數分歧', severity: 'medium', category: 'consistency', explanation: 'Decision 與 Technical 觀察面向出現明顯差距，不宜互相替代。', evidence: { decisionScore: input.decisionScore, technicalScore: input.technicalScore, difference: Math.abs(input.decisionScore - input.technicalScore) }, source: 'GULI Derived' })
  if (input.dateMismatch) add({ id: 'date-mismatch', title: '資料日期不一致', severity: 'high', category: 'data-quality', explanation: '行情、歷史、法人或分析資料的交易日期不一致。', evidence: { dateMismatch: true }, source: 'GULI Data Guard' })
  if (input.stale) add({ id: 'stale-data', title: '資料可能過期', severity: 'high', category: 'data-quality', explanation: '至少一個核心資料集可能不是最近合理交易日。', evidence: { stale: true }, source: 'GULI Data Guard' })
  if (input.historyRecordCount < 60) add({ id: 'insufficient-history', title: '歷史樣本不足', severity: input.historyRecordCount < 20 ? 'high' : 'medium', category: 'data-quality', explanation: '歷史樣本不足以完整判讀中長期技術結構。', evidence: { recordCount: input.historyRecordCount, required: 60 }, source: 'TWSE Official History' })
  return risks.sort((left, right) => severityRank[right.severity] - severityRank[left.severity] || left.id.localeCompare(right.id))
}
