import { ArrowDownRight, ArrowUpRight, BarChart3, Gauge } from 'lucide-react'
import { formatComparison, formatConfidence, formatDecisionScore } from '../../lib/formatters'
import type { DecisionComparison, DecisionResult } from '../../types/decision'
import { Badge } from '../ui/Badge'
import { Button } from '../ui/Button'
import { Card } from '../ui/Card'
import { EmptyState } from '../ui/EmptyState'
import { LoadingState } from '../ui/LoadingState'

export function DecisionRankingSummary({ decisions, comparisons, loading, error, onSelect }: { decisions: DecisionResult[]; comparisons: Map<string, DecisionComparison>; loading: boolean; error: string; onSelect: (decision: DecisionResult) => void }) {
  const scored = decisions.filter((item) => item.score !== null)
  const rankings = [
    { title: 'Decision Top 10', eyebrow: 'STRENGTH', icon: <ArrowUpRight size={17} />, rows: [...scored].sort((a, b) => (b.score ?? 0) - (a.score ?? 0)).slice(0, 10), mode: 'score' as const },
    { title: 'Decision Bottom 10', eyebrow: 'WEAKNESS', icon: <ArrowDownRight size={17} />, rows: [...scored].sort((a, b) => (a.score ?? 0) - (b.score ?? 0)).slice(0, 10), mode: 'score' as const },
    { title: 'Confidence 最低 10', eyebrow: 'DATA CONFIDENCE', icon: <Gauge size={17} />, rows: [...decisions].sort((a, b) => a.confidence - b.confidence).slice(0, 10), mode: 'confidence' as const },
    { title: 'Decision 變化最大 10', eyebrow: 'DAILY CHANGE', icon: <BarChart3 size={17} />, rows: [...decisions].filter((item) => comparisons.get(item.entityId)?.scoreChange !== null && comparisons.get(item.entityId)?.scoreChange !== undefined).sort((a, b) => Math.abs(comparisons.get(b.entityId)?.scoreChange ?? 0) - Math.abs(comparisons.get(a.entityId)?.scoreChange ?? 0)).slice(0, 10), mode: 'change' as const },
  ]
  return <section className="space-y-4" aria-label="個股 Decision 摘要排行"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">STOCK DECISION RADAR</p><h2 className="type-section-title mt-2 font-semibold text-white">個股決策雷達</h2></div><Button variant="ghost" onClick={() => document.getElementById('complete-decision-ranking')?.scrollIntoView({ behavior: 'smooth' })}>查看完整排行</Button></div><div className="grid gap-5 xl:grid-cols-2">{rankings.map((ranking) => <Card key={ranking.title} title={ranking.title} eyebrow={ranking.eyebrow} variant="compact" state={loading ? 'loading' : error ? 'error' : ranking.rows.length ? 'default' : 'empty'}>{loading ? <LoadingState rows={5} /> : error ? <EmptyState title="排行暫時無法顯示" description={error} /> : ranking.rows.length ? <ol>{ranking.rows.map((item, index) => { const comparison = comparisons.get(item.entityId); const primaryFactor = [...item.factors].filter((factor) => factor.contribution !== null).sort((a, b) => Math.abs(b.contribution ?? 0) - Math.abs(a.contribution ?? 0))[0]; return <li key={item.entityId}><button type="button" onClick={() => onSelect(item)} className="grid min-h-[76px] w-full grid-cols-[30px_1fr_auto] items-center gap-3 border-t border-white/[.05] px-4 py-2 text-left first:border-t-0 hover:bg-white/[.025] sm:px-5"><span className={`mono text-sm ${index < 3 ? 'text-brand-300' : 'text-slate-500'}`}>{index + 1}</span><span className="min-w-0"><span className="block truncate text-[15px] font-medium text-white">{item.entityName}</span><span className="mono mt-0.5 block text-xs text-slate-500">{item.entityId} · Decision {formatDecisionScore(item.score)} · Confidence {formatConfidence(item.confidence)}</span><span className="mt-0.5 block truncate text-xs text-slate-500">今日變化 {formatComparison(comparison?.scoreChange)} · {primaryFactor?.name ?? '尚無主要因子'}</span></span><span className="text-right"><span className="mono block text-base text-white">{ranking.mode === 'confidence' ? formatConfidence(item.confidence) : ranking.mode === 'change' ? formatComparison(comparison?.scoreChange) : formatDecisionScore(item.score)}</span><Badge tone={item.direction === 'bullish' ? 'up' : item.direction === 'bearish' ? 'down' : 'neutral'}>{item.label}</Badge><span className="mt-1 block text-xs text-brand-300">查看 Trace</span></span></button></li>})}</ol> : <EmptyState title="尚無可排名資料" description={ranking.mode === 'change' ? '目前只有單一交易日，尚無前期比較資料。' : 'Decision index 沒有符合條件的個股。'} />}</Card>)}</div></section>
}
