import { ArrowDown, ArrowUp, Minus } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import type { IndustrySnapshotItem } from '../../types/industrySnapshot'
import { Badge } from '../ui/Badge'
import { DataTable, NumericCell } from '../ui/DataTable'

const number = (value: number | null, suffix = '') => value === null ? '—' : `${value.toLocaleString('zh-TW', { maximumFractionDigits: 2 })}${suffix}`
export function IndustryRankingTable({ items }: { items: IndustrySnapshotItem[] }) {
  const navigate = useNavigate()
  return <><div className="hidden md:block"><DataTable minWidth={940} containerClassName="rounded-none border-0"><thead><tr>{['排名', '產業', '強度', '排名變化', '1 日', '5 日', '20 日', '法人淨買超', '成交金額', '漲／跌／平', '狀態'].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.industryId} tabIndex={0} onClick={() => navigate(`/industries/${item.industryId}`)} onKeyDown={(event) => { if (event.key === 'Enter') navigate(`/industries/${item.industryId}`) }} className="cursor-pointer outline-none focus:bg-white/[.035]"><td className="mono text-white">#{item.rank}</td><td><p className="text-base font-semibold text-white">{item.industryName}</p><p className="mt-1 text-xs text-slate-500">點擊查看產業詳情</p></td><NumericCell>{item.strengthScore}</NumericCell><td><RankChange value={item.rankChange} /></td>{[item.return1d, item.return5d, item.return20d].map((value, index) => <NumericCell key={index} className={returnTone(value)}>{signed(value, '%')}</NumericCell>)}<NumericCell>{number(item.institutionalNetBuy)}</NumericCell><NumericCell>{item.tradingAmount === null ? '—' : `${(item.tradingAmount / 100_000_000).toFixed(1)} 億`}</NumericCell><NumericCell>{item.advanceCount ?? '—'}／{item.declineCount ?? '—'}／{item.unchangedCount ?? '—'}</NumericCell><td><Badge tone={item.status === '強勢' || item.status === '偏強' ? 'up' : item.status === '弱勢' || item.status === '偏弱' ? 'down' : 'neutral'}>{item.status}</Badge></td></tr>)}</tbody></DataTable></div><div className="space-y-4 p-4 md:hidden">{items.map((item) => <button type="button" key={item.industryId} onClick={() => navigate(`/industries/${item.industryId}`)} className="mobile-data-card block min-h-0 w-full text-left"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-slate-500">排名 #{item.rank}</p><p className="mt-1 text-base font-semibold text-white">{item.industryName}</p></div><Badge tone={item.status === '強勢' || item.status === '偏強' ? 'up' : item.status === '弱勢' || item.status === '偏弱' ? 'down' : 'neutral'}>{item.status}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3"><MobileMetric label="產業強度" value={number(item.strengthScore)} /><MobileMetric label="排名變化" valueElement={<RankChange value={item.rankChange} />} /><MobileMetric label="1 日" value={signed(item.return1d, '%')} tone={returnTone(item.return1d)} /><MobileMetric label="5 日" value={signed(item.return5d, '%')} tone={returnTone(item.return5d)} /></div></button>)}</div></>
}

function RankChange({ value }: { value: number | null }) { return value === null || value === 0 ? <span className="inline-flex items-center gap-1 text-slate-400"><Minus size={15} />持平</span> : value > 0 ? <span className="inline-flex items-center gap-1 text-red-300"><ArrowUp size={15} />上升 {value}</span> : <span className="inline-flex items-center gap-1 text-emerald-300"><ArrowDown size={15} />下降 {Math.abs(value)}</span> }
function MobileMetric({ label, value, valueElement, tone = 'text-white' }: { label: string; value?: string; valueElement?: React.ReactNode; tone?: string }) { return <div className="rounded-xl bg-white/[.025] p-3"><p className="text-xs text-slate-500">{label}</p><div className={`mono mt-2 text-base ${tone}`}>{valueElement ?? value}</div></div> }
const signed = (value: number | null, suffix = '') => value === null ? '—' : `${value > 0 ? '+' : ''}${value.toLocaleString('zh-TW', { maximumFractionDigits: 2 })}${suffix}`
const returnTone = (value: number | null) => value === null || value === 0 ? 'text-slate-300' : value > 0 ? 'text-red-300' : 'text-emerald-300'
