import { ArrowDown, ArrowRight, ArrowUp } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { calculateStockHealth } from '../../services/stockHealthService'
import type { Stock } from '../../types/stock'
import { DataTable, NumericCell } from '../ui/DataTable'

export function PeerComparison({ stock, universe }: { stock: Stock; universe: Stock[] }) {
  const navigate = useNavigate()
  const same = universe.filter((item) => item.industry === stock.industry)
  const related = universe.filter((item) => item.industry !== stock.industry).sort((a, b) => Math.abs(b.industryStrength - stock.industryStrength) - Math.abs(a.industryStrength - stock.industryStrength))
  const peers = [...same, ...related].filter((item, index, all) => all.findIndex((candidate) => candidate.symbol === item.symbol) === index).slice(0, 5).map((item) => ({ stock: item, health: calculateStockHealth(item, universe) })).sort((a, b) => b.health.totalScore - a.health.totalScore)
  return <div className="overflow-hidden"><div className="hidden md:block"><DataTable minWidth={720} containerClassName="rounded-none border-0"><thead><tr><th>排名／股票</th><th className="numeric">健康分數</th><th className="numeric">近 5 日</th><th className="numeric">法人買賣超</th><th className="numeric">成交量變化</th><th aria-label="操作" /></tr></thead><tbody>{peers.map((entry, index) => <tr key={entry.stock.symbol} onClick={() => navigate(`/stock/${entry.stock.symbol}`)} className="cursor-pointer"><td><p className="text-base font-semibold text-white">{index + 1}. {entry.stock.name}</p><p className="mono mt-1 text-sm text-slate-500">{entry.stock.symbol}</p></td><NumericCell className="text-brand-300">{entry.health.totalScore}</NumericCell><NumericCell><Change value={return5(entry.stock)} /></NumericCell><NumericCell>{entry.stock.institutions.total.toFixed(1)} 張</NumericCell><NumericCell>{volumeChange(entry.stock).toFixed(1)}%</NumericCell><td><button type="button" aria-label={`查看 ${entry.stock.name}`} className="icon-button grid place-items-center rounded-xl text-slate-400 hover:text-brand-300"><ArrowRight size={18} /></button></td></tr>)}</tbody></DataTable></div><div className="space-y-4 p-4 md:hidden">{peers.map((entry, index) => <button key={entry.stock.symbol} type="button" onClick={() => navigate(`/stock/${entry.stock.symbol}`)} className="mobile-data-card block min-h-0 w-full text-left"><div className="flex items-center justify-between"><span className="text-base font-semibold text-white">{index + 1}. {entry.stock.name} <span className="mono text-sm text-slate-500">{entry.stock.symbol}</span></span><span className="mono text-xl text-brand-300">{entry.health.totalScore}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-sm text-slate-400"><span>5 日<br /><Change value={return5(entry.stock)} /></span><span>法人<br />{entry.stock.institutions.total.toFixed(0)}</span><span>量變<br />{volumeChange(entry.stock).toFixed(0)}%</span></div></button>)}</div><p className="border-t border-[var(--border-subtle)] px-5 py-4 text-sm leading-6 text-slate-500">優先列出同產業個股；樣本不足時，以產業強度相近個股補足五檔比較。</p></div>
}

const return5 = (stock: Stock) => { const history = stock.priceHistory.slice(-6); return (history[history.length - 1].value / history[0].value - 1) * 100 }
const volumeChange = (stock: Stock) => { const recent = stock.priceHistory.slice(-5).reduce((sum, item) => sum + (item.volume ?? 0), 0) / 5; const prior = stock.priceHistory.slice(-10, -5).reduce((sum, item) => sum + (item.volume ?? 0), 0) / 5; return prior ? (recent / prior - 1) * 100 : 0 }
function Change({ value }: { value: number }) { return <span className={`inline-flex items-center justify-end gap-1 ${value >= 0 ? 'text-red-300' : 'text-emerald-300'}`}>{value >= 0 ? <ArrowUp size={14} /> : <ArrowDown size={14} />}{value > 0 ? '+' : ''}{value.toFixed(2)}%</span> }
