import { ArrowRight } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { calculateStockHealth } from '../../services/stockHealthService'
import type { Stock } from '../../types/stock'

export function PeerComparison({ stock, universe }: { stock: Stock; universe: Stock[] }) {
  const navigate = useNavigate()
  const same = universe.filter((item) => item.industry === stock.industry)
  const related = universe.filter((item) => item.industry !== stock.industry).sort((a, b) => Math.abs(b.industryStrength - stock.industryStrength) - Math.abs(a.industryStrength - stock.industryStrength))
  const peers = [...same, ...related].filter((item, index, all) => all.findIndex((candidate) => candidate.symbol === item.symbol) === index).slice(0, 5).map((item) => ({ stock: item, health: calculateStockHealth(item, universe) })).sort((a, b) => b.health.totalScore - a.health.totalScore)
  return <div className="overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[650px] text-left"><thead><tr className="border-b border-[var(--border-subtle)] text-[9px] uppercase tracking-wider text-slate-600"><th className="px-5 py-3">排名／股票</th><th>健康分數</th><th>近 5 日</th><th>法人買賣超</th><th>成交量變化</th><th></th></tr></thead><tbody>{peers.map((entry, index) => <PeerRow key={entry.stock.symbol} entry={entry} rank={index + 1} onClick={() => navigate(`/stock/${entry.stock.symbol}`)}/>)}</tbody></table></div><div className="space-y-3 p-4 md:hidden">{peers.map((entry, index) => <button key={entry.stock.symbol} type="button" onClick={() => navigate(`/stock/${entry.stock.symbol}`)} className="w-full rounded-xl border border-[var(--border-subtle)] p-4 text-left"><div className="flex items-center justify-between"><span className="text-xs font-medium text-white">{index + 1}. {entry.stock.name} <span className="mono text-slate-600">{entry.stock.symbol}</span></span><span className="mono text-brand-300">{entry.health.totalScore}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-[9px] text-slate-500"><span>5 日 {return5(entry.stock).toFixed(1)}%</span><span>法人 {entry.stock.institutions.total.toFixed(0)}</span><span>量變 {volumeChange(entry.stock).toFixed(0)}%</span></div></button>)}</div><p className="border-t border-[var(--border-subtle)] px-5 py-3 text-[9px] text-slate-600">優先列出同產業個股；樣本不足時，以產業強度相近個股補足五檔比較。</p></div>
}

const return5 = (stock: Stock) => { const history = stock.priceHistory.slice(-6); return (history[history.length - 1].value / history[0].value - 1) * 100 }
const volumeChange = (stock: Stock) => { const recent = stock.priceHistory.slice(-5).reduce((sum, item) => sum + (item.volume ?? 0), 0) / 5; const prior = stock.priceHistory.slice(-10, -5).reduce((sum, item) => sum + (item.volume ?? 0), 0) / 5; return prior ? (recent / prior - 1) * 100 : 0 }
function PeerRow({ entry, rank, onClick }: { entry: { stock: Stock; health: ReturnType<typeof calculateStockHealth> }; rank: number; onClick: () => void }) { return <tr className="border-b border-[var(--border-subtle)] text-[11px] text-slate-400 hover:bg-white/[.02]"><td className="px-5 py-3"><button type="button" onClick={onClick} className="flex items-center gap-3 text-left"><span className="mono text-slate-600">{rank}</span><span><b className="font-medium text-white">{entry.stock.name}</b><br/><span className="mono text-[9px]">{entry.stock.symbol}</span></span></button></td><td className="mono text-brand-300">{entry.health.totalScore}</td><td className={return5(entry.stock) >= 0 ? 'text-red-300' : 'text-emerald-300'}>{return5(entry.stock).toFixed(2)}%</td><td>{entry.stock.institutions.total.toFixed(1)} 張</td><td>{volumeChange(entry.stock).toFixed(1)}%</td><td><button type="button" onClick={onClick} aria-label={`查看 ${entry.stock.name}`} className="min-h-11 px-3 text-slate-500 hover:text-brand-300"><ArrowRight size={14}/></button></td></tr> }
