import type { StockSnapshotArchiveIndex, StockSnapshotDailyIndex, StockSnapshotItem } from '../../types/stockSnapshot'
type Fetcher=(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>
export class StockSnapshotStorageError extends Error { constructor(public readonly code:'NOT_FOUND'|'INVALID_JSON'|'INVALID_SCHEMA'|'NETWORK',message:string){super(message);this.name='StockSnapshotStorageError'} }
const dateOk=(value:string|undefined)=>!!value&&/^\d{4}-\d{2}-\d{2}$/.test(value)
const scoreOk=(value:number|null|undefined)=>value===null||(typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=100)
export const isStockSnapshotItem=(value:unknown):value is StockSnapshotItem=>{if(!value||typeof value!=='object')return false;const item=value as Partial<StockSnapshotItem>;return !!item.symbol&&item.market==='TWSE'&&item.instrumentType==='stock'&&dateOk(item.tradeDate)&&!!item.quote&&scoreOk(item.snapshotScore)&&scoreOk(item.priceStrengthScore)&&scoreOk(item.liquidityScore)&&scoreOk(item.valuationRiskScore)&&Array.isArray(item.risks)&&Array.isArray(item.warnings)}
export const isStockSnapshotDailyIndex=(value:unknown):value is StockSnapshotDailyIndex=>{if(!value||typeof value!=='object')return false;const index=value as Partial<StockSnapshotDailyIndex>;return index.schemaVersion==='1.0'&&index.market==='TWSE'&&dateOk(index.tradeDate)&&Array.isArray(index.records)&&index.records.every((item)=>!!item.symbol&&scoreOk(item.snapshotScore)&&scoreOk(item.priceStrengthScore)&&scoreOk(item.liquidityScore))}
const isArchive=(value:unknown):value is StockSnapshotArchiveIndex=>!!value&&typeof value==='object'&&(value as Partial<StockSnapshotArchiveIndex>).schemaVersion==='1.0'&&Array.isArray((value as Partial<StockSnapshotArchiveIndex>).snapshots)
export class StockSnapshotStorage { private cache=new Map<string,{value:unknown;expires:number}>(); constructor(private readonly fetcher:Fetcher=globalThis.fetch.bind(globalThis),private readonly baseUrl=import.meta.env.BASE_URL,private readonly ttlMs=300_000){} private async read<T>(path:string,validator:(value:unknown)=>value is T){const hit=this.cache.get(path);if(hit&&hit.expires>Date.now())return hit.value as T;let response:Response;try{response=await this.fetcher(`${this.baseUrl}${path}`,{cache:'no-cache',headers:{accept:'application/json'}})}catch{throw new StockSnapshotStorageError('NETWORK','無法讀取個股快照資料。')}if(!response.ok)throw new StockSnapshotStorageError('NOT_FOUND',`找不到個股快照：${path}`);let data:unknown;try{data=await response.json()}catch{throw new StockSnapshotStorageError('INVALID_JSON','個股快照不是有效 JSON。')}if(!validator(data))throw new StockSnapshotStorageError('INVALID_SCHEMA','個股快照格式驗證失敗。');this.cache.set(path,{value:data,expires:Date.now()+this.ttlMs});return data} getArchiveIndex(){return this.read('data/stock-history/index.json',isArchive)} getLatestIndex(){return this.read('data/stock-history/latest.json',isStockSnapshotDailyIndex)} getBySymbol(symbol:string,date:string){return this.read(`data/stock-history/${date}/stocks/${encodeURIComponent(symbol)}.json`,isStockSnapshotItem)} clearCache(){this.cache.clear()} }
