import { describe, expect, it, vi } from 'vitest'
import { MemoryCache } from '../../cache/MemoryCache'
import { CachePolicy } from '../../cache/CachePolicy'
import { TWSEStockHistoryProvider } from '../TWSEStockHistoryProvider'
import { StockHistoryRepository } from '../../repositories/StockHistoryRepository'
import type { OfficialStockHistory, StockHistoryIndex } from '../../types/officialStockHistory'

const history: OfficialStockHistory = { schemaVersion: '1.0', symbol: '2330', name: '台積電', market: 'TWSE', source: 'TWSE', sourceUrl: 'https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY', fetchedAt: '2026-07-17T08:00:00.000Z', firstTradeDate: '2026-07-16', lastTradeDate: '2026-07-16', recordCount: 1, status: 'official', warnings: [], prices: [{ tradeDate: '2026-07-16', open: 100, high: 102, low: 99, close: 101, change: 1, volume: 1000, tradingAmount: 100000, transactionCount: 100 }] }
const index: StockHistoryIndex = { schemaVersion: '1.0', source: 'TWSE', updatedAt: '2026-07-17T08:00:00.000Z', targetTradingDays: 250, symbols: [{ symbol: '2330', name: '台積電', path: 'data/twse-stock-history/stocks/2330.json', firstTradeDate: '2026-07-16', lastTradeDate: '2026-07-16', recordCount: 1, status: 'official', stale: false, warnings: [], technical: { aboveMa20: null, rsiOverbought: null, macdGoldenCross: null, volumeExpansion: null, indicatorComputable: false } }], summary: { availableSymbols: 1, averageRecordCount: 1, complete250Count: 0, staleCount: 0, failedSymbols: [], technicalSampleSize: 0, aboveMa20Count: 0, rsiOverboughtCount: 0, macdGoldenCrossCount: 0, volumeExpansionCount: 0 } }

describe('TWSEStockHistoryProvider and repository cache', () => {
  it('uses the GitHub Pages base path', async () => { const fetcher = vi.fn(async () => new Response(JSON.stringify(index))); const provider = new TWSEStockHistoryProvider(fetcher, '/guli/'); await provider.getIndex(); expect(fetcher).toHaveBeenCalledWith('/guli/data/twse-stock-history/index.json', expect.any(Object)) })
  it('resolves the 2330 production JSON URL', () => { const provider = new TWSEStockHistoryProvider(async () => new Response(), '/guli/'); expect(provider.getResolvedHistoryUrl('2330', 'https://jacksonchen272.github.io')).toBe('https://jacksonchen272.github.io/guli/data/twse-stock-history/stocks/2330.json') })
  it('reports missing data without throwing from status', async () => { const provider = new TWSEStockHistoryProvider(async () => new Response('', { status: 404 }), '/guli/'); expect((await provider.getDatasetStatus()).available).toBe(false) })
  it('rejects invalid history dataset', async () => { const provider = new TWSEStockHistoryProvider(async () => new Response(JSON.stringify({ symbol: '2330' })), '/guli/'); await expect(provider.getHistory('2330')).rejects.toThrow('未通過資料驗證') })
  it('caches a valid index in provider', async () => { const fetcher = vi.fn(async () => new Response(JSON.stringify(index))); const provider = new TWSEStockHistoryProvider(fetcher, '/guli/'); await provider.getIndex(); await provider.getIndex(); expect(fetcher).toHaveBeenCalledTimes(1) })
  it('repository does not load the same valid symbol twice', async () => { const fetcher = vi.fn(async (input: RequestInfo | URL) => new Response(JSON.stringify(String(input).endsWith('index.json') ? index : history))); const repo = new StockHistoryRepository(new TWSEStockHistoryProvider(fetcher, '/guli/'), new MemoryCache(), new CachePolicy()); await repo.getHistory('2330'); await repo.getHistory('2330'); expect(fetcher).toHaveBeenCalledTimes(1) })
  it('clearCache symbol forces a new read', async () => { const fetcher = vi.fn(async () => new Response(JSON.stringify(history))); const repo = new StockHistoryRepository(new TWSEStockHistoryProvider(fetcher, '/guli/'), new MemoryCache(), new CachePolicy()); await repo.getHistory('2330'); repo.clearCache('2330'); await repo.getHistory('2330'); expect(fetcher).toHaveBeenCalledTimes(2) })
  it('dataset status reports coverage percentages', async () => { const provider = new TWSEStockHistoryProvider(async () => new Response(JSON.stringify(index)), '/guli/'); const status = await provider.getDatasetStatus(); expect(status.availableSymbols).toBe(1); expect(status.complete250Percent).toBe(0); expect(status.indicatorComputablePercent).toBe(0) })
})
