import { describe, expect, it, vi } from 'vitest'
import { CachePolicy } from '../../cache/CachePolicy'
import { MemoryCache } from '../../cache/MemoryCache'
import { InstitutionRepository } from '../../repositories/InstitutionRepository'
import type { OfficialInstitutionalDataset } from '../../types/officialInstitutionalData'
import { TWSEInstitutionalProvider } from '../TWSEInstitutionalProvider'
const record = (symbol: string, total: number) => ({ symbol, name: symbol, foreignNetShares: total, trustNetShares: 0, dealerNetShares: 0, totalNetShares: total, tradeDate: '2026-07-16', source: 'TWSE' as const, fetchedAt: '2026-07-16T08:00:00.000Z', status: 'official' as const, warnings: [] })
const dataset: OfficialInstitutionalDataset = { schemaVersion: '1.0', market: 'TWSE', tradeDate: '2026-07-16', fetchedAt: '2026-07-16T08:00:00.000Z', units: { marketTotals: 'TWD', stockNet: 'shares' }, marketTotals: { foreign: { buyAmount: 10, sellAmount: 8, netAmount: 2 }, trust: { buyAmount: 5, sellAmount: 4, netAmount: 1 }, dealer: { buyAmount: 3, sellAmount: 5, netAmount: -2 }, total: { buyAmount: 18, sellAmount: 17, netAmount: 1 } }, records: [record('2330', 1000), record('2603', -500), ...Array.from({ length: 98 }, (_, index) => record(String(3000 + index), index))], source: { name: '臺灣證券交易所（TWSE）', marketEndpoint: 'https://www.twse.com.tw/rwd/zh/fund/BFI82U', stockEndpoint: 'https://www.twse.com.tw/rwd/zh/fund/T86' }, status: 'official', warnings: [] }
const response = (body: unknown, ok = true) => new Response(JSON.stringify(body), { status: ok ? 200 : 404, headers: { 'content-type': 'application/json' } })
describe('TWSEInstitutionalProvider and InstitutionRepository', () => {
  it('使用 GitHub Pages BASE_URL 讀取 latest JSON', async () => { const fetcher = vi.fn(async () => response(dataset)); const provider = new TWSEInstitutionalProvider(fetcher, '/guli/'); await provider.getLatestDataset(); expect(fetcher).toHaveBeenCalledWith('/guli/data/twse-institutional/latest.json', expect.any(Object)) })
  it('有效 cache 不重複讀取 JSON', async () => { const fetcher = vi.fn(async () => response(dataset)); const provider = new TWSEInstitutionalProvider(fetcher, '/guli/', 60_000); await provider.getLatestDataset(); await provider.getLatestDataset(); expect(fetcher).toHaveBeenCalledTimes(1) })
  it('clearCache 後重新讀取', async () => { const fetcher = vi.fn(async () => response(dataset)); const provider = new TWSEInstitutionalProvider(fetcher, '/guli/'); await provider.getLatestDataset(); provider.clearCache(); await provider.getLatestDataset(); expect(fetcher).toHaveBeenCalledTimes(2) })
  it('JSON 不存在回傳 Missing 狀態而非白畫面', async () => { const provider = new TWSEInstitutionalProvider(async () => response({}, false), '/guli/'); const status = await provider.getStatus(); expect(status.available).toBe(false); expect(status.status).toBe('missing') })
  it('無效資料集回傳 Missing 狀態', async () => { const provider = new TWSEInstitutionalProvider(async () => response({ bad: true }), '/guli/'); expect((await provider.getStatus()).status).toBe('missing') })
  it('Repository 回傳市場總計', async () => { const provider = new TWSEInstitutionalProvider(async () => response(dataset), '/guli/'); const repo = new InstitutionRepository(new MemoryCache(), new CachePolicy(), provider); expect((await repo.getMarketTotals())?.total.netAmount).toBe(1) })
  it('Repository 買超排行由高到低', async () => { const provider = new TWSEInstitutionalProvider(async () => response(dataset), '/guli/'); const repo = new InstitutionRepository(new MemoryCache(), new CachePolicy(), provider); expect((await repo.getTopNetBuy('total', 2)).map((item) => item.symbol)).toEqual(['2330', '3097']) })
  it('Repository 賣超排行由低到高', async () => { const provider = new TWSEInstitutionalProvider(async () => response(dataset), '/guli/'); const repo = new InstitutionRepository(new MemoryCache(), new CachePolicy(), provider); expect((await repo.getTopNetSell('total', 1))[0].symbol).toBe('2603') })
  it('Repository 找不到個股時回傳 null', async () => { const provider = new TWSEInstitutionalProvider(async () => response(dataset), '/guli/'); const repo = new InstitutionRepository(new MemoryCache(), new CachePolicy(), provider); expect(await repo.getStockInstitutional('9999')).toBeNull() })
  it('Repository 共用 cache', async () => { const fetcher = vi.fn(async () => response(dataset)); const repo = new InstitutionRepository(new MemoryCache(), new CachePolicy(), new TWSEInstitutionalProvider(fetcher, '/guli/')); await repo.getMarketTotals(); await repo.getTopNetBuy('foreign'); expect(fetcher).toHaveBeenCalledTimes(1) })
})
