import { AlertTriangle, ArrowDown, ArrowUp, Eye, Search, SlidersHorizontal, Trash2 } from 'lucide-react'
import { observationStatusMeta, riskLevelMeta } from '../../config/watchlistDashboard'
import { formatConfidence, formatDateTime, formatDecisionScore, formatSignedChange, formatStockPrice, formatWholeScore } from '../../lib/formatters'
import { useWatchlistStore } from '../../stores/watchlistStore'
import type { DecisionDirection } from '../../types/decision'
import type { WatchlistDashboardFilters, WatchlistDashboardRow } from '../../types/watchlistDashboard'
import { Badge } from '../ui/Badge'
import { Button } from '../ui/Button'
import { Card } from '../ui/Card'
import { DataTable, NumericCell } from '../ui/DataTable'
import { Select } from '../ui/Select'

export function filterAndSortWatchlistRows(rows: WatchlistDashboardRow[], filters: WatchlistDashboardFilters) {
  const query = filters.query.trim().toLowerCase()
  const filtered = rows.filter((row) => {
    const searchable = [row.symbol, row.name, row.industry, row.observationStatus, observationStatusMeta[row.observationStatus].label, ...row.tags].join(' ').toLowerCase()
    const confidenceMatch = filters.confidence === 'all' || filters.confidence === 'high' && row.confidence >= 70 || filters.confidence === 'medium' && row.confidence >= 40 && row.confidence < 70 || filters.confidence === 'low' && row.confidence < 40
    const riskMatch = filters.risk === 'all' || filters.risk === 'high' && row.riskLevel === 'high' || filters.risk === 'low' && row.riskLevel === 'low'
    return (!query || searchable.includes(query)) && (row.decisionScore ?? -1) >= filters.minimumDecision && confidenceMatch && (filters.source === 'all' || row.source === filters.source) && riskMatch && (filters.industry === 'all' || row.industry === filters.industry)
  })
  const value = (row: WatchlistDashboardRow) => ({ decision: row.decisionScore ?? -1, confidence: row.confidence, snapshot: row.snapshotScore ?? -1, health: row.healthScore ?? -1, change: row.changePercent ?? -Infinity, volume: row.volume ?? -1, risk: row.riskScore, updatedAt: Date.parse(row.updatedAt) || 0, status: observationStatusMeta[row.observationStatus].order } satisfies Record<WatchlistDashboardFilters['sort'], number>)[filters.sort]
  return filtered.sort((a, b) => value(b) - value(a) || a.symbol.localeCompare(b.symbol))
}

export function WatchlistDashboardTable({ rows, filters, onFiltersChange, onSelect, onRemove }: { rows: WatchlistDashboardRow[]; filters: WatchlistDashboardFilters; onFiltersChange: (filters: WatchlistDashboardFilters) => void; onSelect: (row: WatchlistDashboardRow) => void; onRemove: (symbol: string) => void }) {
  const groups = useWatchlistStore((state) => state.groups)
  const items = useWatchlistStore((state) => state.items)
  const industries = [...new Set(rows.map((row) => row.industry))].sort((a, b) => a.localeCompare(b, 'zh-Hant'))
  const visible = filterAndSortWatchlistRows([...rows], filters)
  const groupName = (symbol: string) => { const groupId = items.find((item) => item.symbol === symbol)?.groupId; return groups.find((group) => group.id === groupId)?.name ?? '未分組' }
  const patch = <Key extends keyof WatchlistDashboardFilters>(key: Key, value: WatchlistDashboardFilters[Key]) => onFiltersChange({ ...filters, [key]: value })
  return <Card title="自選股清單" eyebrow="WATCHLIST INTELLIGENCE" action={<span className="text-sm text-slate-400">顯示 {visible.length}／{rows.length} 檔</span>}>
    <div className="border-b border-white/[.06] p-5 sm:p-6"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[minmax(220px,1.4fr)_repeat(6,minmax(126px,.65fr))]"><label className="relative"><span className="sr-only">搜尋自選股</span><Search size={17} className="absolute left-3 top-3.5 text-slate-400" /><input value={filters.query} onChange={(event) => patch('query', event.target.value)} placeholder="搜尋代號、名稱、標籤或狀態" className="h-11 w-full rounded-xl border border-white/[.08] bg-[#0d1317] pl-10 pr-3 text-[15px] text-white outline-none focus:border-brand-400/40" /></label><Select value={filters.minimumDecision} onChange={(event) => patch('minimumDecision', Number(event.target.value))} aria-label="Decision 篩選"><option value={0}>全部 Decision</option><option value={80}>Decision 80+</option><option value={60}>Decision 60+</option><option value={40}>Decision 40+</option></Select><Select value={filters.confidence} onChange={(event) => patch('confidence', event.target.value as WatchlistDashboardFilters['confidence'])} aria-label="Confidence 篩選"><option value="all">全部 Confidence</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></Select><Select value={filters.source} onChange={(event) => patch('source', event.target.value as WatchlistDashboardFilters['source'])} aria-label="資料來源篩選"><option value="all">全部來源</option><option value="official">官方資料</option><option value="mock">Mock</option><option value="fallback">Fallback</option></Select><Select value={filters.risk} onChange={(event) => patch('risk', event.target.value as WatchlistDashboardFilters['risk'])} aria-label="風險篩選"><option value="all">全部風險</option><option value="high">高風險</option><option value="low">低風險</option></Select><Select value={filters.industry} onChange={(event) => patch('industry', event.target.value)} aria-label="產業篩選"><option value="all">全部產業</option>{industries.map((industry) => <option key={industry} value={industry}>{industry}</option>)}</Select><Select value={filters.sort} onChange={(event) => patch('sort', event.target.value as WatchlistDashboardFilters['sort'])} aria-label="排序方式"><option value="decision">Decision 排序</option><option value="confidence">Confidence 排序</option><option value="snapshot">Snapshot 排序</option><option value="health">健康排序</option><option value="change">漲跌排序</option><option value="volume">成交量排序</option><option value="risk">風險排序</option><option value="updatedAt">更新時間排序</option><option value="status">Observation Status</option></Select></div><p className="mt-3 flex items-center gap-2 text-xs text-slate-500"><SlidersHorizontal size={14} />點擊股票可在右側開啟完整觀察資料，不需離開本頁。</p></div>

    <div className="hidden lg:block"><DataTable minWidth={1460} watchlist containerClassName="rounded-none border-0"><thead><tr><th>股票</th><th className="numeric">現價／漲跌</th><th className="numeric">Decision</th><th className="numeric">Confidence</th><th className="numeric">健康</th><th className="numeric">Snapshot</th><th>風險</th><th>最新訊號</th><th>更新</th><th aria-label="操作" /></tr></thead><tbody>{visible.map((row) => <tr key={row.symbol} onClick={() => onSelect(row)} tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSelect(row) } }} className="cursor-pointer outline-none focus:bg-white/[.04]"><td><p className="text-base font-semibold text-white">{row.name}</p><p className="mono mt-1 text-[13px] text-slate-400">{row.symbol} · {groupName(row.symbol)} · {observationStatusMeta[row.observationStatus].label}</p><p className="mt-1 text-xs text-slate-500">{row.industry} · {row.sourceLabel}</p></td><NumericCell><p className="text-base text-white">{formatStockPrice(row.price)}</p><PriceChange value={row.changePercent} /></NumericCell><NumericCell><ScoreProgress value={row.decisionScore} label="Decision" change={row.decisionChange} decision /></NumericCell><NumericCell><ScoreProgress value={row.confidence} label="Confidence" percent /></NumericCell><NumericCell><span className="text-base text-white">{formatWholeScore(row.healthScore)}</span></NumericCell><NumericCell><ScoreProgress value={row.snapshotScore} label="Snapshot" change={row.snapshotChange} /></NumericCell><td><Risk row={row} /></td><td><p className="max-w-[190px] truncate text-sm text-slate-200">{row.tags[0] ?? row.decision.label}</p><p className="mt-1 max-w-[190px] truncate text-xs text-slate-500">{directionText('市場', row.marketDirection)} · {directionText('產業', row.industryDirection)}</p></td><td><span className="text-sm text-slate-400">{formatDateTime(row.updatedAt)}</span></td><td><div className="flex items-center gap-1"><button type="button" aria-label={`查看 ${row.name} 詳情`} onClick={(event) => { event.stopPropagation(); onSelect(row) }} className="icon-button grid place-items-center rounded-xl text-slate-400 hover:bg-brand-400/10 hover:text-brand-300"><Eye size={18} /></button><button type="button" aria-label={`移除 ${row.name}`} onClick={(event) => { event.stopPropagation(); onRemove(row.symbol) }} className="icon-button grid place-items-center rounded-xl text-slate-400 hover:bg-red-400/10 hover:text-red-300"><Trash2 size={18} /></button></div></td></tr>)}</tbody></DataTable></div>

    <div className="space-y-4 p-4 sm:p-5 lg:hidden">{visible.map((row) => <article key={row.symbol} className="mobile-data-card"><button type="button" onClick={() => onSelect(row)} className="min-h-0 w-full text-left"><div className="flex items-start justify-between gap-3"><div><p className="text-base font-semibold text-white">{row.name}</p><p className="mono mt-1 text-[13px] text-slate-400">{row.symbol} · {groupName(row.symbol)}</p><p className="mt-1 text-sm text-slate-500">{row.industry} · {row.sourceLabel}</p></div><Badge tone={observationStatusMeta[row.observationStatus].tone}>{observationStatusMeta[row.observationStatus].label}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3"><MobileMetric label="現價" value={formatStockPrice(row.price)} /><MobileMetric label="今日漲跌" valueElement={<PriceChange value={row.changePercent} />} /><MobileMetric label="Decision" value={formatDecisionScore(row.decisionScore)} progress={row.decisionScore} /><MobileMetric label="Confidence" value={formatConfidence(row.confidence)} progress={row.confidence} /><MobileMetric label="健康" value={formatWholeScore(row.healthScore)} /><MobileMetric label="Snapshot" value={formatWholeScore(row.snapshotScore)} progress={row.snapshotScore} /></div><div className="mt-4 rounded-xl bg-white/[.025] p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs text-slate-500">最新訊號 · {formatDateTime(row.updatedAt)}</p><Risk row={row} /></div><p className="mt-2 text-sm text-slate-200">{row.tags[0] ?? row.decision.label}</p><p className="mt-1 text-xs text-slate-500">{directionText('市場', row.marketDirection)} · {directionText('產業', row.industryDirection)}</p></div></button><Button type="button" variant="danger" onClick={() => onRemove(row.symbol)} className="mt-4 w-full" icon={<Trash2 size={16} />}>移除自選股</Button></article>)}</div>
    {!visible.length && <div className="p-12 text-center text-sm text-slate-500">目前篩選條件下沒有符合的自選股。</div>}
  </Card>
}

function ScoreProgress({ value, label, change, decision = false, percent = false }: { value: number | null; label: string; change?: number | null; decision?: boolean; percent?: boolean }) { const display = percent ? formatConfidence(value) : decision ? formatDecisionScore(value) : formatWholeScore(value); return <div className="ml-auto w-[92px]"><div className="flex items-center justify-end gap-2"><span className="text-base text-white">{display}</span>{change !== undefined && change !== null && <span className={`text-xs ${tone(change)}`}>{formatComparisonShort(change)}</span>}</div><div className="score-progress mt-2" role="progressbar" aria-label={`${label} ${display}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value === null ? undefined : Math.round(value)}><span style={{ width: `${Math.max(0, Math.min(100, value ?? 0))}%` }} /></div></div> }
function PriceChange({ value }: { value: number | null }) { return <span className={`mt-1 inline-flex items-center justify-end gap-1 text-sm ${tone(value)}`}>{value !== null && value > 0 ? <ArrowUp size={14} /> : value !== null && value < 0 ? <ArrowDown size={14} /> : null}{value === null ? '—' : `${value >= 0 ? '上漲 ' : '下跌 '}${formatSignedChange(value, '%')}`}</span> }
function Risk({ row }: { row: WatchlistDashboardRow }) { return <Badge tone={riskLevelMeta[row.riskLevel].tone}><AlertTriangle size={14} className="mr-1" />{riskLevelMeta[row.riskLevel].label} {row.riskScore}</Badge> }
function MobileMetric({ label, value, valueElement, progress }: { label: string; value?: string; valueElement?: React.ReactNode; progress?: number | null }) { return <div className="rounded-xl border border-white/[.05] bg-white/[.018] p-3"><p className="text-xs text-slate-500">{label}</p><div className="mono mt-2 text-base text-white">{valueElement ?? value}</div>{progress !== undefined && <div className="score-progress mt-2" role="progressbar" aria-label={`${label} ${value}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress === null ? undefined : Math.round(progress)}><span style={{ width: `${Math.max(0, Math.min(100, progress ?? 0))}%` }} /></div>}</div> }
const formatComparisonShort = (value: number) => `${value > 0 ? '↑+' : value < 0 ? '↓' : '→'}${value.toFixed(1)}`
const tone = (value: number | null) => value === null || value === 0 ? 'text-slate-400' : value > 0 ? 'text-red-300' : 'text-emerald-300'
const directionText = (label: string, value: DecisionDirection) => `${label}${value === 'bullish' ? '偏強 ↑' : value === 'bearish' ? '偏弱 ↓' : value === 'neutral' ? '中性 →' : '未知'}`
