import { Edit3, ExternalLink, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { marketRepository } from '../../services/dataRepository'
import { calculateStockHealth } from '../../services/stockHealthService'
import { useWatchlistStore } from '../../stores/watchlistStore'
import type { WatchlistItem } from '../../types/stock'
import { Badge } from '../ui/Badge'
import { Button } from '../ui/Button'
import { Drawer } from '../ui/Drawer'
import { Select } from '../ui/Select'

const mockStocks = marketRepository.getStocks()

export function WatchlistTable({ search, groupId }: { search: string; groupId: string }) {
  const navigate = useNavigate(); const items = useWatchlistStore((state) => state.items); const groups = useWatchlistStore((state) => state.groups); const remove = useWatchlistStore((state) => state.remove); const [editing, setEditing] = useState<WatchlistItem | null>(null)
  const rows = useMemo(() => items.map((item) => ({ item, stock: mockStocks.find((stock) => stock.symbol === item.symbol) })).filter((row) => row.stock && (groupId === 'all' || row.item.groupId === groupId) && (!search || row.stock.symbol.includes(search) || row.stock.name.includes(search))).map((row) => ({ ...row, stock: row.stock!, health: calculateStockHealth(row.stock!, mockStocks) })), [items, groupId, search])
  return <><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[980px] text-left"><thead><tr className="border-b border-[var(--border-subtle)] text-[9px] uppercase tracking-wider text-slate-600"><th className="px-5 py-3">股票</th><th>群組</th><th>現價／漲跌</th><th>健康分數</th><th>法人狀態</th><th>觀察／停損／停利</th><th>最新訊號</th><th></th></tr></thead><tbody>{rows.map(({ item, stock, health }) => <tr key={item.symbol} className="border-b border-[var(--border-subtle)] text-[11px] text-slate-400 hover:bg-white/[.018]"><td className="px-5 py-4"><button type="button" onClick={() => navigate(`/stock/${stock.symbol}`)} className="text-left"><b className="font-medium text-white">{stock.name}</b><span className="mono ml-2 text-[9px] text-slate-600">{stock.symbol}</span><p className="mt-1 max-w-[180px] truncate text-[9px] text-slate-600">{item.note || '尚未新增備註'}</p></button></td><td>{groups.find((group) => group.id === item.groupId)?.name}</td><td><span className="mono text-white">{stock.price}</span><br/><span className={stock.changePercent >= 0 ? 'text-red-300' : 'text-emerald-300'}>{stock.changePercent > 0 ? '+' : ''}{stock.changePercent.toFixed(2)}%</span></td><td><span className="mono text-brand-300">{health.totalScore}</span> <span className="text-[9px]">{health.grade}</span></td><td><Badge tone={stock.institutions.total >= 0 ? 'up' : 'down'}>{stock.institutions.total >= 0 ? '法人買超' : '法人賣超'}</Badge></td><td className="mono text-[9px]">{item.targetPrice ?? '—'}／{item.stopLossPrice ?? '—'}／{item.takeProfitPrice ?? '—'}</td><td>{health.risks[0]?.label ?? '趨勢正常'}</td><td><div className="flex"><button type="button" onClick={() => setEditing(item)} className="grid min-h-11 min-w-11 place-items-center text-slate-500 hover:text-brand-300" aria-label={`編輯 ${stock.name}`}><Edit3 size={14}/></button><button type="button" onClick={() => remove(item.symbol)} className="grid min-h-11 min-w-11 place-items-center text-slate-500 hover:text-red-300" aria-label={`移除 ${stock.name}`}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>
    <div className="space-y-3 p-4 lg:hidden">{rows.map(({ item, stock, health }) => <article key={item.symbol} className="rounded-2xl border border-[var(--border-subtle)] p-4"><div className="flex items-start justify-between"><button type="button" onClick={() => navigate(`/stock/${stock.symbol}`)} className="text-left"><p className="text-sm font-semibold text-white">{stock.name} <span className="mono text-[10px] text-slate-600">{stock.symbol}</span></p><p className="mt-1 text-[10px] text-slate-500">{groups.find((group) => group.id === item.groupId)?.name}</p></button><div className="text-right"><p className="mono text-sm text-white">{stock.price}</p><p className={stock.changePercent >= 0 ? 'text-red-300' : 'text-emerald-300'}>{stock.changePercent > 0 ? '+' : ''}{stock.changePercent.toFixed(2)}%</p></div></div><div className="mt-4 grid grid-cols-3 gap-2"><Small label="健康" value={`${health.totalScore} ${health.grade}`}/><Small label="法人" value={stock.institutions.total >= 0 ? '買超' : '賣超'}/><Small label="距觀察價" value={item.targetPrice ? `${((stock.price / item.targetPrice - 1) * 100).toFixed(1)}%` : '—'}/></div><p className="mt-3 text-[10px] text-slate-500">{item.note || '尚未新增備註'}</p><div className="mt-3 flex gap-2"><Button size="sm" className="flex-1" onClick={() => setEditing(item)} icon={<Edit3 size={13}/>}>編輯</Button><Button size="sm" variant="ghost" onClick={() => navigate(`/stock/${stock.symbol}`)} icon={<ExternalLink size={13}/>}>健檢</Button><Button size="sm" variant="danger" onClick={() => remove(item.symbol)} aria-label={`移除 ${stock.name}`} icon={<Trash2 size={13}/>}/></div></article>)}</div>
    {!rows.length && <div className="p-10 text-center text-sm text-slate-600">目前篩選條件下沒有自選股。</div>}<EditWatchlistDrawer item={editing} groups={groups} onClose={() => setEditing(null)}/></>
}

function Small({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/[.025] p-2"><p className="text-[8px] text-slate-600">{label}</p><p className="mt-1 text-[10px] text-slate-300">{value}</p></div> }
function EditWatchlistDrawer({ item, groups, onClose }: { item: WatchlistItem | null; groups: ReturnType<typeof useWatchlistStore.getState>['groups']; onClose: () => void }) { const edit = useWatchlistStore((state) => state.edit); const [draft, setDraft] = useState<WatchlistItem | null>(null); const current = draft?.symbol === item?.symbol ? draft : item; if (!current) return <Drawer open={false} onClose={onClose} title="編輯自選股"><div/></Drawer>; const setField = (changes: Partial<WatchlistItem>) => setDraft({ ...current, ...changes }); const save = () => { edit(current.symbol, { groupId: current.groupId, note: current.note, targetPrice: current.targetPrice, stopLossPrice: current.stopLossPrice, takeProfitPrice: current.takeProfitPrice }); setDraft(null); onClose() }; return <Drawer open onClose={onClose} title={`編輯 ${current.symbol}`}><div className="space-y-5 p-5"><Field label="自選群組"><Select className="w-full" value={current.groupId} onChange={(event) => setField({ groupId: event.target.value })}>{groups.map((group) => <option value={group.id} key={group.id}>{group.name}</option>)}</Select></Field><Field label="備註"><textarea value={current.note} onChange={(event) => setField({ note: event.target.value })} className="min-h-24 w-full rounded-xl border border-[var(--border-subtle)] bg-[#0d1317] p-3 text-xs text-white outline-none focus:border-brand-400/30"/></Field><div className="grid gap-4 sm:grid-cols-3"><NumberField label="觀察價" value={current.targetPrice} onChange={(value) => setField({ targetPrice: value })}/><NumberField label="停損參考價" value={current.stopLossPrice} onChange={(value) => setField({ stopLossPrice: value })}/><NumberField label="停利參考價" value={current.takeProfitPrice} onChange={(value) => setField({ takeProfitPrice: value })}/></div><Button className="w-full" onClick={save}>儲存變更</Button></div></Drawer> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-[10px] text-slate-500">{label}</span>{children}</label> }
function NumberField({ label, value, onChange }: { label: string; value?: number; onChange: (value?: number) => void }) { return <Field label={label}><input type="number" inputMode="decimal" value={value ?? ''} onChange={(event) => onChange(event.target.value ? Number(event.target.value) : undefined)} className="h-11 w-full rounded-xl border border-[var(--border-subtle)] bg-[#0d1317] px-3 text-xs text-white outline-none focus:border-brand-400/30"/></Field> }
