import { GitBranch, Minus, TrendingDown, TrendingUp } from 'lucide-react'
import { useState } from 'react'
import { observationStatusMeta, riskLevelMeta } from '../../config/watchlistDashboard'
import type { DecisionDirection } from '../../types/decision'
import type { WatchlistDashboardRow } from '../../types/watchlistDashboard'
import { DecisionTraceDrawer } from '../decision/DecisionTraceDrawer'
import { Badge } from '../ui/Badge'
import { Button } from '../ui/Button'
import { Drawer } from '../ui/Drawer'

export const getWatchlistDrawerSections = (row: WatchlistDashboardRow | null) => row ? ['Decision', '健康', 'Snapshot', '市場', '產業', 'Confidence', '主要正向因子', '主要扣分因子', 'Observation Timeline', 'Decision Trace'] : []

export function WatchlistDetailDrawer({ row, onClose }: { row: WatchlistDashboardRow | null; onClose: () => void }) {
  const [traceOpen, setTraceOpen] = useState(false)
  return <><Drawer open={row !== null} onClose={onClose} title={row ? `${row.symbol} ${row.name} · 智慧觀察` : '智慧觀察'}>{row && <div className="space-y-6 p-5 sm:p-6">
    <div className="rounded-2xl border border-brand-400/20 bg-brand-400/[.035] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-slate-400">Observation Status</p><p className="mt-1 text-2xl font-semibold text-white">{observationStatusMeta[row.observationStatus].label}</p></div><Badge tone={observationStatusMeta[row.observationStatus].tone}>{row.observationStatus}</Badge></div><p className="mt-3 text-[15px] leading-7 text-slate-400">{observationStatusMeta[row.observationStatus].description}</p></div>
    <div className="grid grid-cols-2 gap-3"><Metric label="Decision" value={format(row.decisionScore)} change={row.decisionChange} /><Metric label="Confidence" value={`${row.confidence}%`} change={row.confidenceChange} /><Metric label="健康分數" value={format(row.healthScore)} /><Metric label="Snapshot" value={format(row.snapshotScore)} change={row.snapshotChange} /><Metric label="Watchlist Score" value={`${format(row.watchlistScore)} · ${row.watchlistGrade}`} /><Metric label="風險分數" value={`${row.riskScore} · ${riskLevelMeta[row.riskLevel].label}`} /></div>
    <section className="rounded-xl border border-white/[.06] p-5"><h3 className="mb-4 text-lg font-semibold text-white">市場與產業方向</h3><div className="grid grid-cols-2 gap-3"><Direction label="市場" direction={row.marketDirection} /><Direction label="產業" direction={row.industryDirection} /></div><div className="mt-4 flex flex-wrap gap-2"><Badge tone={row.source === 'official' ? 'info' : row.source === 'fallback' ? 'warning' : 'neutral'}>{row.sourceLabel}</Badge><Badge tone="neutral">更新 {formatTime(row.updatedAt)}</Badge></div></section>
    <FactorSection title="主要正向因子" factors={row.topPositiveFactors.map((factor) => ({ name: factor.name, value: factor.contribution, detail: factor.explanation }))} positive />
    <FactorSection title="主要扣分因子" factors={row.topNegativeFactors.map((factor) => ({ name: factor.name, value: factor.contribution, detail: factor.explanation }))} />
    <section className="rounded-xl border border-white/[.06] p-5"><h3 className="mb-4 text-lg font-semibold text-white">最近 Snapshot</h3><div className="grid grid-cols-2 gap-4 text-sm"><Pair label="交易日" value={row.snapshot.tradeDate} /><Pair label="收盤價" value={format(row.snapshot.quote.close)} /><Pair label="今日漲跌" value={percent(row.snapshot.quote.changePercent)} /><Pair label="流動性" value={format(row.snapshot.liquidityScore)} /><Pair label="價格強度" value={format(row.snapshot.priceStrengthScore)} /><Pair label="風險數" value={`${row.snapshot.risks.length}`} /></div></section>
    <section className="rounded-xl border border-white/[.06] p-5"><h3 className="mb-4 text-lg font-semibold text-white">Observation Timeline</h3><div className="space-y-4">{row.timeline.map((entry) => <div key={`${entry.tradeDate}-${entry.isCurrent}`} className="relative border-l border-white/[.1] pl-5"><span className={`absolute -left-1 top-1 h-2 w-2 rounded-full ${entry.isCurrent ? 'bg-brand-400' : 'bg-slate-600'}`} /><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium text-white">{entry.isCurrent ? '本期' : '前期'} · {entry.tradeDate}</span>{entry.decisionChange !== null && <Change value={entry.decisionChange} />}</div><p className="mt-2 text-sm leading-6 text-slate-400">Decision {format(entry.decisionScore)} · Confidence {entry.confidence ?? '—'} · Snapshot {format(entry.snapshotScore)} · 風險 {entry.riskCount}</p></div>)}</div>{row.timeline.length === 1 && <p className="mt-4 text-sm leading-6 text-amber-200/90">目前靜態資料只有一個交易日；下一期 Snapshot 產生後會自動顯示差異。</p>}</section>
    <Button variant="primary" className="w-full" onClick={() => setTraceOpen(true)} icon={<GitBranch size={18} />}>開啟 Decision Trace</Button>
    <p className="text-xs leading-6 text-slate-500">Observation Status 與 Today Action 僅用於資料觀察，不構成買賣或投資建議。</p>
  </div>}</Drawer><DecisionTraceDrawer decision={row?.decision ?? null} open={traceOpen && row !== null} onClose={() => setTraceOpen(false)} /></>
}

function Metric({ label, value, change }: { label: string; value: string; change?: number | null }) { return <div className="rounded-xl border border-white/[.06] p-4"><p className="text-sm text-slate-400">{label}</p><div className="mt-2 flex flex-wrap items-end justify-between gap-2"><p className="mono text-2xl text-white">{value}</p>{change !== undefined && change !== null && <Change value={change} />}</div></div> }
function Direction({ label, direction }: { label: string; direction: DecisionDirection }) { const positive = direction === 'bullish'; const negative = direction === 'bearish'; return <div className="rounded-xl bg-white/[.025] p-4"><p className="text-sm text-slate-400">{label}</p><p className={`mt-2 flex items-center gap-2 text-base font-medium ${positive ? 'text-red-300' : negative ? 'text-emerald-300' : 'text-slate-300'}`}>{positive ? <TrendingUp size={18} /> : negative ? <TrendingDown size={18} /> : <Minus size={18} />}{positive ? '偏強' : negative ? '偏弱' : direction === 'neutral' ? '中性' : '資料不足'}</p></div> }
function FactorSection({ title, factors, positive = false }: { title: string; factors: Array<{ name: string; value: number | null; detail: string }>; positive?: boolean }) { return <section className="rounded-xl border border-white/[.06] p-5"><h3 className="mb-4 text-lg font-semibold text-white">{title}</h3><div className="space-y-3">{factors.map((factor) => <div key={factor.name} className="rounded-xl bg-white/[.025] p-4"><div className="flex justify-between gap-3"><span className="text-[15px] font-medium text-slate-200">{factor.name}</span><span className={`mono text-sm ${positive ? 'text-red-300' : 'text-emerald-300'}`}>{factor.value === null ? '—' : `${factor.value > 0 ? '+' : ''}${factor.value.toFixed(2)}`}</span></div><p className="mt-2 text-sm leading-6 text-slate-400">{factor.detail}</p></div>)}{!factors.length && <p className="text-sm text-slate-500">目前沒有符合的規則因子。</p>}</div></section> }
function Pair({ label, value }: { label: string; value: string }) { return <div><span className="text-slate-500">{label}</span><p className="mono mt-1 text-base text-slate-200">{value}</p></div> }
function Change({ value }: { value: number }) { return <span className={`mono text-sm ${value > 0 ? 'text-red-300' : value < 0 ? 'text-emerald-300' : 'text-slate-400'}`}>{value > 0 ? '↑ +' : value < 0 ? '↓ ' : ''}{value.toFixed(1)}</span> }
const format = (value: number | null) => value === null ? '—' : value.toFixed(1)
const percent = (value: number | null) => value === null ? '—' : `${value > 0 ? '+' : ''}${value.toFixed(2)}%`
const formatTime = (value: string) => Number.isNaN(Date.parse(value)) ? value : new Date(value).toLocaleString('zh-TW', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false })
