import { describe, expect, it } from 'vitest'
import { mockIndustries } from '../../../data/mockIndustries'
import { mockStocks } from '../../../data/mockStocks'
import { IndustrySnapshotGenerator } from '../IndustrySnapshotGenerator'
const generator = new IndustrySnapshotGenerator()
const create = () => generator.generate({ tradeDate: '2026-07-13', generatedAt: '2026-07-13T08:00:00.000Z', industries: mockIndustries, stocks: mockStocks })
describe('IndustrySnapshotGenerator', () => {
  it('uses the required weighted formula', () => { const item = create().industries[0]; const adjustment = 100 - item.riskScore; expect(item.strengthScore).toBe(Math.round(item.capitalFlowScore*.30 + item.momentumScore*.25 + item.breadthScore*.20 + item.relativeStrengthScore*.15 + adjustment*.10)) })
  it('keeps all scores between zero and one hundred', () => { for (const item of create().industries) for (const score of [item.strengthScore,item.momentumScore,item.capitalFlowScore,item.breadthScore,item.relativeStrengthScore,item.riskScore]) { expect(score).toBeGreaterThanOrEqual(0); expect(score).toBeLessThanOrEqual(100) } })
  it('assigns unique sequential ranks', () => { const ranks=create().industries.map((item)=>item.rank); expect(ranks).toEqual(ranks.map((_,index)=>index+1)); expect(new Set(ranks).size).toBe(ranks.length) })
  it('ranks a stronger constructed industry above a weak one', () => { const strong={...mockIndustries[0],id:'strong',name:'強勢測試',capitalFlow:30,momentum:15,stockSymbols:[mockStocks[0].symbol]}; const weak={...mockIndustries[1],id:'weak',name:'弱勢測試',capitalFlow:-30,momentum:-15,stockSymbols:[mockStocks.find((stock)=>stock.changePercent<0)!.symbol]}; const stocks=[{...mockStocks[0],industry:'強勢測試',changePercent:6,institutions:{foreign:500,trust:300,dealer:100,total:900},rsi:65,volatility:1},{...mockStocks.find((stock)=>stock.changePercent<0)!,industry:'弱勢測試',changePercent:-6,institutions:{foreign:-500,trust:-300,dealer:-100,total:-900},rsi:35,volatility:4}]; const result=generator.generate({tradeDate:'2026-07-13',industries:[strong,weak],stocks}); expect(result.industries[0].industryId).toBe('strong') })
  it('raises capital flow score when institutional net buying increases', () => { const base=mockStocks[0]; const industry={...mockIndustries[0],name:'測試產業',stockSymbols:[base.symbol]}; const low=generator.generate({tradeDate:'2026-07-13',industries:[industry],stocks:[{...base,industry:'測試產業',institutions:{foreign:-300,trust:0,dealer:0,total:-300}}]}).industries[0]; const high=generator.generate({tradeDate:'2026-07-13',industries:[industry],stocks:[{...base,industry:'測試產業',institutions:{foreign:800,trust:0,dealer:0,total:800}}]}).industries[0]; expect(high.capitalFlowScore).toBeGreaterThan(low.capitalFlowScore) })
  it('raises breadth score when more constituents advance', () => { const stocks=mockStocks.slice(0,3).map((stock)=>({...stock,industry:'廣度測試'})); const industry={...mockIndustries[0],id:'breadth',name:'廣度測試',stockSymbols:stocks.map((stock)=>stock.symbol)}; const falling=generator.generate({tradeDate:'2026-07-13',industries:[industry],stocks:stocks.map((stock)=>({...stock,changePercent:-1}))}).industries[0]; const rising=generator.generate({tradeDate:'2026-07-13',industries:[industry],stocks:stocks.map((stock)=>({...stock,changePercent:1}))}).industries[0]; expect(rising.breadthScore).toBeGreaterThan(falling.breadthScore) })
  it('increases risk score for high volatility and never overlaps leaders and laggards', () => { const normal=create().industries.find((item)=>item.leaderStocks.length&&item.laggardStocks.length)!; const members=mockStocks.filter((stock)=>normal.leaderStocks.concat(normal.laggardStocks).some((entry)=>entry.symbol===stock.symbol)); const industry=mockIndustries.find((item)=>item.id===normal.industryId)!; const risky=generator.generate({tradeDate:'2026-07-13',industries:[industry],stocks:members.map((stock)=>({...stock,volatility:8,rsi:85}))}).industries[0]; expect(risky.riskScore).toBeGreaterThan(normal.riskScore); expect(risky.leaderStocks.some((leader)=>risky.laggardStocks.some((laggard)=>laggard.symbol===leader.symbol))).toBe(false) })
})
