import { Bell, Menu, Moon, Sun } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { allPages } from '../../config/navigation'
import { GlobalStockSearch } from '../search/GlobalStockSearch'

export function TopBar({ onMenuClick }: { onMenuClick: () => void }) {
  const { pathname } = useLocation()
  const [softTheme, setSoftTheme] = useState(false)
  const current = pathname.startsWith('/stock/') ? { eyebrow: 'Stock Analysis', title: '個股分析' } : allPages.find((item) => item.path === pathname) ?? allPages[0]
  useEffect(() => { document.documentElement.classList.toggle('theme-soft', softTheme); return () => document.documentElement.classList.remove('theme-soft') }, [softTheme])
  return <header className="sticky top-0 z-30 flex h-[68px] items-center justify-between border-b border-[var(--border-subtle)] bg-[color-mix(in_srgb,var(--bg-page)_92%,transparent)] px-4 backdrop-blur-xl sm:px-6 lg:px-8"><div className="flex min-w-0 items-center gap-3"><button type="button" onClick={onMenuClick} className="grid h-11 w-11 place-items-center rounded-xl border border-[var(--border-subtle)] text-slate-300 lg:hidden" aria-label="開啟側邊選單"><Menu size={19} /></button><div className="min-w-0"><p className="mono truncate text-[8px] uppercase tracking-[.18em] text-slate-600">{current.eyebrow}</p><h1 className="truncate text-sm font-semibold text-slate-100">{current.title}</h1></div></div><div className="flex items-center gap-2"><div className="mr-1 hidden items-center gap-2 border-r border-[var(--border-subtle)] pr-4 xl:flex"><span className="h-2 w-2 rounded-full bg-slate-500" /><div><p className="text-[10px] font-medium text-slate-300">台股已收盤</p><p className="mono text-[8px] text-slate-600">更新 13:35</p></div></div><GlobalStockSearch /><button type="button" onClick={() => setSoftTheme((value) => !value)} className="grid h-11 w-11 place-items-center rounded-xl border border-[var(--border-subtle)] text-slate-500 transition hover:border-[var(--border-strong)] hover:text-white" aria-label={softTheme ? '切換深色主題' : '切換柔和主題'}>{softTheme ? <Moon size={17} /> : <Sun size={17} />}</button><button type="button" className="relative grid h-11 w-11 place-items-center rounded-xl border border-[var(--border-subtle)] text-slate-500 transition hover:border-[var(--border-strong)] hover:text-white" aria-label="通知"><Bell size={17} /><span className="absolute right-2.5 top-2 h-1.5 w-1.5 rounded-full bg-brand-400" /></button><button type="button" className="hidden h-11 items-center gap-2 rounded-xl border border-[var(--border-subtle)] px-2.5 sm:flex" aria-label="使用者選單"><span className="grid h-7 w-7 place-items-center rounded-lg bg-brand-400/10 text-[10px] font-semibold text-brand-300">OW</span><span className="hidden text-[10px] text-slate-400 2xl:block">Owen</span></button></div></header>
}
