import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

const text = (file: string) => readFile(file, 'utf8')
const pushToMain = /git push[^\n]*(?:HEAD:main|origin\s+main|:main(?:\s|$))/

describe('GitHub Actions stability guard', () => {
  it('deploy only validates, tests, builds and uploads dist', async () => { const workflow = await text('.github/workflows/deploy-pages.yml'); expect(workflow).toContain('npm run data:validate'); expect(workflow).toContain('npm run test:run'); expect(workflow).toContain('npm run build'); expect(workflow).toContain('actions/upload-pages-artifact@'); expect(workflow).toMatch(/path:\s*\.\/dist/); expect(workflow).not.toMatch(/git\s+(?:add|commit|push|pull)/) })
  it('deploy keeps minimal Pages permissions and concurrency', async () => { const workflow = await text('.github/workflows/deploy-pages.yml'); for (const token of ['contents: read', 'pages: write', 'id-token: write', 'group: pages', 'cancel-in-progress: true']) expect(workflow).toContain(token) })
  it('daily update uses its automation branch and one PR', async () => { const workflow = await text('.github/workflows/twse-daily-update.yml'); expect(workflow).toContain('DATA_UPDATE_BRANCH: automation/data-updates'); expect(workflow).toContain('gh pr create'); expect(workflow).toContain('gh pr edit'); expect(workflow).not.toMatch(pushToMain) })
  it('daily update runs official data, incremental history and downstream indexes in order', async () => { const workflow = await text('.github/workflows/twse-daily-update.yml'); const commands = ['data:twse', 'data:twse:stocks', 'data:twse:institutional', 'data:history:backfill', 'data:technical:rebuild', 'data:history:validate', 'screener:generate', 'heatmap:generate']; let previous = -1; for (const command of commands) { const current = workflow.indexOf(`npm run ${command}`, previous + 1); expect(current).toBeGreaterThan(previous); previous = current } })
  it('daily update stages generated data only and skips empty commits', async () => { const workflow = await text('.github/workflows/twse-daily-update.yml'); expect(workflow).toContain('git add public/data data/history reports'); expect(workflow).toContain('git diff --cached --quiet'); expect(workflow).not.toMatch(/git add[^\n]*(?:CHANGELOG|ROADMAP|package\.json|package-lock|src\/|scripts\/|docs\/|Sidebar|Settings)/); expect(workflow).toContain('group: market-data-update'); expect(workflow).toContain('cancel-in-progress: false') })
  it('backfill is manual, bounded and uses a separate automation branch', async () => { const workflow = await text('.github/workflows/twse-history-backfill.yml'); expect(workflow).toContain('workflow_dispatch:'); expect(workflow).not.toContain('push:'); expect(workflow).toContain("default: '50'"); expect(workflow).toContain('BACKFILL_BRANCH: automation/history-backfill'); expect(workflow).toContain('group: stock-history-backfill'); expect(workflow).toContain('cancel-in-progress: false'); expect(workflow).not.toMatch(pushToMain) })
  it('backfill writes generated data and creates or updates a PR', async () => { const workflow = await text('.github/workflows/twse-history-backfill.yml'); expect(workflow).toContain('git add public/data data/history reports'); expect(workflow).toContain('gh pr create'); expect(workflow).toContain('gh pr edit') })
  it('GitHub Pages keeps the Vite base and BrowserRouter basename', async () => { expect(await text('vite.config.ts')).toContain("base: '/guli/'"); expect(await text('src/main.tsx')).toContain('basename="/guli"') })
  it('git check remains non-mutating', async () => { const script = await text('scripts/check-git-state.mjs'); expect(script).toContain('process.exitCode = 1'); expect(script).not.toMatch(/runGit\(\['(?:reset|checkout|pull|push|rebase|commit)'/) })
})
