import { AlertTriangle, CalendarDays, Database, Layers3, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import { DataTrustBanner } from '../components/system/DataTrustBanner'
import { Badge } from '../components/ui/Badge'
import { Card } from '../components/ui/Card'
import { LoadingState } from '../components/ui/LoadingState'
import { SectionHeader } from '../components/ui/SectionHeader'
import { repositoryHub } from '../repositories/RepositoryHub'
import { calculateDataCoverage } from '../services/DataCoverageService'
import type { DataCoverageReport } from '../types/dataCoverage'

export function DataCoverage(){
  const[report,setReport]=useState<DataCoverageReport|null>(null)
  useEffect(()=>{let active=true;void Promise.all([
    repositoryHub.stocks.getOfficialDatasetStatus(),repositoryHub.institutions.getDatasetStatus(),repositoryHub.stocks.getOfficialStocks(),repositoryHub.stockHistory.getDatasetStatus(),repositoryHub.screener.getTechnicalIndex().catch(()=>null),repositoryHub.screener.getDataset().catch(()=>null),repositoryHub.stockHistory.getBackfillProgress().catch(()=>null),repositoryHub.industryMapping.getStatus(),repositoryHub.marketHeatmap.getLatest().catch(()=>null),repositoryHub.industrySnapshots.getLatest().catch(()=>null),
  ]).then(([stocks,institutions,stockRows,history,technical,screener,backfill,mapping,heatmap,industrySnapshot])=>{if(!active)return;const common=stockRows.filter((row)=>/^\d{4}$/.test(row.symbol)&&row.instrumentType==='stock');setReport(calculateDataCoverage({
    marketAvailable:Boolean(repositoryHub.getSnapshot().overview.officialMarket),stockRecords:common.length,targetStocks:Math.max(common.length,1),institutionalRecords:institutions.recordCount,institutionalTarget:Math.max(common.length,1),industryOfficialRecords:mapping.mappedStocks,industryTarget:Math.max(mapping.totalStocks,1),industryMappedStockCount:mapping.mappedStocks,industryUnmappedStockCount:mapping.unmappedStocks,industryCount:mapping.industryCount,industryCoveragePercent:mapping.coverageRate,heatmapStockCount:heatmap?.stocks.length??0,industrySnapshotCount:industrySnapshot?.industries.length??0,industryTechnicalJoinCount:industrySnapshot?.industries.reduce((sum,item)=>sum+(item.technicalSampleCount??0),0)??0,industryDecisionJoinCount:industrySnapshot?.industries.reduce((sum,item)=>sum+(item.decisionSampleCount??0),0)??0,industryMappingUpdatedAt:mapping.fetchedAt,industryMappingStale:mapping.stale,
    historyDays:history.averageRecordCount,historyStockCoverageCount:history.availableSymbols,historyAverageDays:history.averageRecordCount,historyComplete250Percent:history.complete250Percent,indicatorComputablePercent:history.indicatorComputablePercent,historyStaleCount:history.staleCount,historyFailedSymbols:history.failedSymbols,totalCommonStocks:common.length,historyComplete250Count:technical?.complete250Count??0,technicalIndexCount:technical?.sampleCount??0,technicalScoreAvailableCount:technical?.scoreAvailableCount??0,decisionJoinCount:screener?new Set(screener.results.filter((row)=>row.decisionScore!==null).map((row)=>row.symbol)).size:0,institutionalJoinCount:screener?new Set(screener.results.filter((row)=>row.institutionalNet!==null).map((row)=>row.symbol)).size:0,alignedCount:screener?new Set(screener.results.filter((row)=>row.dateAlignmentStatus==='aligned').map((row)=>row.symbol)).size:0,mismatchedCount:screener?new Set(screener.results.filter((row)=>row.dateAlignmentStatus==='mismatched').map((row)=>row.symbol)).size:0,backfillCompleted:backfill?.completedSymbols??0,backfillTotal:backfill?.totalSymbols??0,backfillStatus:backfill?.status??'尚未啟動',updatedAt:history.updatedAt??institutions.fetchedAt??stocks.fetchedAt,stale:stocks.stale||institutions.stale||history.staleCount>0,
  }))});return()=>{active=false}},[])

  if(!report)return <Card><LoadingState rows={6}/></Card>
  const metrics=[['市場資料',report.marketOfficialPercent],['個股行情',report.stockOfficialPercent],['法人資料',report.institutionalOfficialPercent],['產業分類',report.industryOfficialPercent]] as const
  const industryMetrics=[['普通股總數',report.industryMappedStockCount+report.industryUnmappedStockCount,'檔'],['官方已分類',report.industryMappedStockCount,'檔'],['未分類',report.industryUnmappedStockCount,'檔'],['官方產業數',report.industryCount,'類'],['官方覆蓋率',report.industryCoveragePercent,'%'],['Heatmap 股票',report.heatmapStockCount,'檔'],['產業 Snapshot',report.industrySnapshotCount,'類'],['Technical joins',report.industryTechnicalJoinCount,'筆'],['Decision joins',report.industryDecisionJoinCount,'筆']] as const
  const historyMetrics=[['歷史行情股票',report.historyStockCoverageCount,'檔'],['平均歷史天數',report.historyAverageDays,'天'],['250 日完整率',report.historyComplete250Percent,'%'],['技術指標可算率',report.indicatorComputablePercent,'%']] as const
  return <div className="space-y-6">
    <SectionHeader eyebrow="BETA DATA COVERAGE" title="資料覆蓋率" description="清楚區分官方資料、規則推導、模擬與尚未取得欄位；樣本數就是實際可用筆數。"/>
    <DataTrustBanner sources={['official','derived','mock']} stale={report.stale}/>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value])=><Card key={label}><div className="p-5"><div className="flex items-center justify-between"><Database size={18} className="text-brand-300"/><Badge tone={value===100?'brand':value?'warning':'neutral'}>{value===100?'Official':value?'Partial':'Missing'}</Badge></div><p className="mono mt-5 text-3xl text-white">{value}%</p><p className="mt-2 text-sm text-slate-400">{label}</p></div></Card>)}</section>
    <Card title="官方產業分類覆蓋" eyebrow="TWSE INDUSTRY MAPPING" action={<Badge tone={report.industryMappingStale?'warning':'info'}>{report.industryMappingStale?'Stale':'TWSE Official'}</Badge>}><div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-5">{industryMetrics.map(([label,value,unit])=><Metric key={label} label={label} value={value} unit={unit}/>)}</div><div className="flex flex-wrap gap-4 border-t border-white/[.06] px-5 py-4 text-xs text-slate-500"><span className="flex items-center gap-2"><Layers3 size={14}/>分類更新 {report.industryMappingUpdatedAt??'尚未取得'}</span><span>未分類股票不以名稱猜測產業</span></div></Card>
    <Card title="TWSE 個股歷史行情覆蓋" eyebrow="HISTORICAL PRICE FOUNDATION" action={<Badge tone="info">TWSE Official History</Badge>}><div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-4">{historyMetrics.map(([label,value,unit])=><div key={label} className="rounded-xl border border-white/[.06] p-4"><CalendarDays size={16} className="text-brand-300"/><p className="mono mt-3 text-2xl text-white">{value}<span className="ml-1 text-xs text-slate-500">{unit}</span></p><p className="mt-2 text-xs text-slate-500">{label}</p></div>)}</div></Card>
    <Card title="資料來源分層" eyebrow="PROVENANCE"><div className="grid gap-5 p-5 lg:grid-cols-3"><FieldList title="Mock" items={report.mockFields}/><FieldList title="Derived" items={report.derivedFields}/><FieldList title="Missing" items={report.missingFields}/></div></Card>
    <Card title="公開測試資料保護" eyebrow="BETA GUARD"><div className="flex gap-3 p-5 text-sm leading-7 text-slate-300"><ShieldCheck className="mt-1 shrink-0 text-brand-300" size={18}/><p>市場、個股、法人與產業分類優先使用 TWSE 官方盤後或公開資料；分析分數與產業強度是 GULI 固定規則推導。缺值保留為 null，不會補造行情。</p>{report.stale&&<AlertTriangle className="mt-1 shrink-0 text-amber-300" size={18}/>}</div></Card>
  </div>
}

function Metric({label,value,unit}:{label:string;value:number;unit:string}){return <div className="rounded-xl border border-white/[.06] p-4"><p className="text-xs text-slate-500">{label}</p><p className="mono mt-2 text-2xl text-white">{value}<span className="ml-1 text-[10px] text-slate-600">{unit}</span></p></div>}
function FieldList({title,items}:{title:string;items:string[]}){return <section><h3 className="text-sm font-semibold text-white">{title}</h3><ul className="mt-3 space-y-2">{items.length?items.map((item)=><li key={item} className="rounded-lg border border-white/[.06] px-3 py-2 text-xs text-slate-400">{item}</li>):<li className="text-xs text-slate-600">無</li>}</ul></section>}
