import { Database, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import { DataTrustBanner } from '../components/system/DataTrustBanner'
import { Badge } from '../components/ui/Badge'
import { Card } from '../components/ui/Card'
import { LoadingState } from '../components/ui/LoadingState'
import { SectionHeader } from '../components/ui/SectionHeader'
import { repositoryHub } from '../repositories/RepositoryHub'
import { calculateDataCoverage } from '../services/DataCoverageService'
import type { DataCoverageReport } from '../types/dataCoverage'
export function DataCoverage() { const [report, setReport] = useState<DataCoverageReport | null>(null); useEffect(() => { let active = true; void Promise.all([repositoryHub.stocks.getOfficialDatasetStatus(), repositoryHub.institutions.getDatasetStatus(), repositoryHub.stocks.getOfficialStocks()]).then(([stocks, institutions, stockRows]) => { if (active) setReport(calculateDataCoverage({ marketAvailable: !!repositoryHub.getSnapshot().overview.officialMarket, stockRecords: stockRows.length, targetStocks: Math.max(stockRows.length, 1), institutionalRecords: institutions.recordCount, institutionalTarget: Math.max(stockRows.length, 1), industryOfficialRecords: 0, industryTarget: 12, historyDays: repositoryHub.getSnapshot().overview.officialMarket?.tradingHistory.length ?? 0, updatedAt: institutions.fetchedAt ?? stocks.fetchedAt, stale: stocks.stale || institutions.stale })) }); return () => { active = false } }, []); if (!report) return <Card><LoadingState rows={6}/></Card>; const metrics = [['市場資料官方覆蓋率', report.marketOfficialPercent], ['個股行情官方覆蓋率', report.stockOfficialPercent], ['法人資料官方覆蓋率', report.institutionalOfficialPercent], ['產業資料官方覆蓋率', report.industryOfficialPercent]] as const; return <div className="space-y-6"><SectionHeader eyebrow="BETA DATA COVERAGE" title="資料覆蓋率" description="公開測試期間，逐項揭露 official、derived、mock、fallback、stale 與 missing。"/><DataTrustBanner sources={['official', 'derived', 'mock']} stale={report.stale}/><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value]) => <Card key={label}><div className="p-5"><div className="flex items-center justify-between"><Database size={18} className="text-brand-300"/><Badge tone={value === 100 ? 'brand' : value ? 'warning' : 'neutral'}>{value === 100 ? 'Official' : value ? 'Mixed' : 'Missing'}</Badge></div><p className="mono mt-5 text-3xl text-white">{value}%</p><p className="mt-2 text-sm text-slate-400">{label}</p></div></Card>)}</section><Card title="欄位來源清單" eyebrow="PROVENANCE"><div className="grid gap-5 p-5 lg:grid-cols-3"><FieldList title="Mock" items={report.mockFields}/><FieldList title="Derived" items={report.derivedFields}/><FieldList title="Missing" items={report.missingFields}/></div><div className="flex flex-wrap gap-4 border-t border-white/[.06] px-5 py-4 text-xs text-slate-500"><span>歷史行情覆蓋：{report.historyDays} 日</span><span>最近更新：{report.updatedAt ?? '尚未取得'}</span><span>Stale：{report.stale ? '是' : '否'}</span></div></Card><Card title="公開測試資料政策" eyebrow="BETA GUARD"><div className="flex gap-3 p-5 text-sm leading-7 text-slate-300"><ShieldCheck className="mt-1 shrink-0 text-brand-300" size={18}/><p>Mock 數值不會標示為官方行情；缺失欄位顯示「尚未取得」；所有規則型分數均標示 Derived，並保留非投資建議聲明。</p></div></Card></div> }
function FieldList({ title, items }: { title: string; items: string[] }) { return <section><h3 className="text-sm font-semibold text-white">{title}</h3><ul className="mt-3 space-y-2">{items.length ? items.map((item) => <li key={item} className="rounded-lg border border-white/[.06] px-3 py-2 text-xs text-slate-400">{item}</li>) : <li className="text-xs text-slate-600">無</li>}</ul></section> }
