import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { IndustryLeaderList } from '../components/industry/IndustryLeaderList'
import { IndustryRankHistoryChart } from '../components/industry/IndustryRankHistoryChart'
import { IndustryRiskPanel } from '../components/industry/IndustryRiskPanel'
import { IndustryStrengthGauge } from '../components/industry/IndustryStrengthGauge'
import { IndustryTrendChart } from '../components/industry/IndustryTrendChart'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Disclaimer } from '../components/ui/Disclaimer'
import { EmptyState } from '../components/ui/EmptyState'
import { LoadingState } from '../components/ui/LoadingState'
import { SectionHeader } from '../components/ui/SectionHeader'
import { industrySnapshotService } from '../services/industrySnapshot/IndustrySnapshotService'
import type { IndustrySnapshotItem } from '../types/industrySnapshot'
export function IndustryDetail() { const { industryId = '' } = useParams(); const navigate = useNavigate(); const [history, setHistory] = useState<Array<{tradeDate:string;item:IndustrySnapshotItem}>>([]); const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; void industrySnapshotService.getIndustryHistory(industryId, 20).then((value) => { if (active) { setHistory(value); setLoading(false) } }).catch(() => { if (active) setLoading(false) }); return () => { active = false } }, [industryId])
  const latest = history[0]?.item; const chronological = useMemo(() => [...history].reverse(), [history]); if (loading) return <div className="panel p-5"><LoadingState rows={8}/></div>; if (!latest) return <div className="panel"><EmptyState title="找不到產業資料" description="此產業可能尚未納入目前的快照。"/><div className="p-5"><Button onClick={() => navigate('/industries')}>返回產業分析</Button></div></div>
  const scoreCards = [['資金流',latest.capitalFlowScore],['動能',latest.momentumScore],['市場廣度',latest.breadthScore],['相對強度',latest.relativeStrengthScore],['風險',latest.riskScore]] as const
  return <div className="space-y-5"><SectionHeader eyebrow="INDUSTRY DETAIL" title={latest.industryName} description={`產業排名 #${latest.rank} · ${latest.status} · 快照日期 ${history[0].tradeDate}`}/><div className="grid gap-5 xl:grid-cols-12"><Card className="p-5 xl:col-span-4"><IndustryStrengthGauge score={latest.strengthScore}/></Card><div className="grid gap-3 sm:grid-cols-2 xl:col-span-8 xl:grid-cols-5">{scoreCards.map(([label,score]) => <div key={label} className="panel p-4"><p className="text-[9px] text-slate-600">{label}</p><p className="mono mt-2 text-2xl text-white">{score}</p></div>)}</div></div><div className="grid gap-5 xl:grid-cols-2"><Card title="強度趨勢" eyebrow="STRENGTH"><div className="p-5"><IndustryTrendChart values={chronological.map((entry) => entry.item.strengthScore)}/></div></Card><Card title="排名歷史" eyebrow="RANK HISTORY"><div className="p-5"><IndustryRankHistoryChart ranks={chronological.map((entry) => ({date:entry.tradeDate,rank:entry.item.rank}))}/></div></Card></div><div className="grid gap-5 xl:grid-cols-3"><Card title="法人與量價" eyebrow="CAPITAL"><div className="grid grid-cols-2 gap-3 p-5 text-[11px]"><div><p className="text-slate-600">法人淨買超</p><p className="mono mt-1 text-white">{latest.institutionalNetBuy?.toLocaleString() ?? '—'}</p></div><div><p className="text-slate-600">成交金額</p><p className="mono mt-1 text-white">{latest.tradingAmount === null ? '—' : `${(latest.tradingAmount/1e8).toFixed(1)} 億`}</p></div><div><p className="text-slate-600">5 日報酬</p><p className="mono mt-1 text-white">{latest.return5d?.toFixed(2) ?? '—'}%</p></div><div><p className="text-slate-600">20 日報酬</p><p className="mono mt-1 text-white">{latest.return20d?.toFixed(2) ?? '—'}%</p></div></div></Card><Card title="領漲成分股" eyebrow="LEADERS"><div className="p-5"><IndustryLeaderList title="領漲" stocks={latest.leaderStocks}/></div></Card><Card title="落後成分股" eyebrow="LAGGARDS"><div className="p-5"><IndustryLeaderList title="落後" stocks={latest.laggardStocks}/></div></Card></div><Card title="產業風險" eyebrow="RISKS"><div className="p-5"><IndustryRiskPanel risks={latest.risks}/></div></Card><div className="panel p-4 text-[10px] leading-5 text-slate-600"><p>來源：{latest.sources.map((source) => `${source.name}（${source.type}）`).join('、')} · 更新：{history[0].tradeDate}</p><Disclaimer>本內容採模擬產業、個股與法人資料依規則計算，僅供資訊參考，不構成投資建議。</Disclaimer></div></div> }
