import { AlertTriangle, Check, Database, LockKeyhole, ShieldCheck } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { SectionHeader } from '../components/ui/SectionHeader'
import { providerFactory } from '../providers/ProviderFactory'
import type { ProviderId } from '../providers/ProviderTypes'
import { repositoryHub } from '../repositories/RepositoryHub'
import { useBetaModeStore } from '../stores/betaModeStore'
import type { DataPlatformStatus } from '../types/dataPlatformStatus'
import type { IndustryMappingDatasetStatusResult } from '../types/officialIndustryMapping'
import type { SearchCoverage } from '../types/search'

export function Settings() {
  const navigate = useNavigate()
  const [activeId, setActiveId] = useState<ProviderId>(providerFactory.getActiveId())
  const [platform, setPlatform] = useState<DataPlatformStatus | null>(null)
  const [mapping, setMapping] = useState<IndustryMappingDatasetStatusResult | null>(null)
  const [searchCoverage, setSearchCoverage] = useState<SearchCoverage | null>(null)
  const [message, setMessage] = useState('正在驗證已部署的 TWSE 靜態 JSON。')
  const [loading, setLoading] = useState(false)
  const publicBetaMode = useBetaModeStore((state) => state.publicBetaMode)
  const setPublicBetaMode = useBetaModeStore((state) => state.setPublicBetaMode)
  const loadPlatform = useCallback(async (force = false) => { const [status, mappingStatus] = await Promise.all([repositoryHub.getPlatformDataStatus(force), force ? repositoryHub.industryMapping.refresh().then(() => repositoryHub.industryMapping.getStatus()).catch(() => repositoryHub.industryMapping.getStatus()) : repositoryHub.industryMapping.getStatus()]); setPlatform(status); setMapping(mappingStatus); setActiveId(status.providerId); setMessage(status.migrationNotice ?? status.summary); return status }, [])
  useEffect(() => { let active = true; void Promise.all([repositoryHub.getPlatformDataStatus(), repositoryHub.industryMapping.getStatus(), repositoryHub.stockDataStatus.getCoverage()]).then(([status, mappingStatus, coverage]) => { if (!active) return; setPlatform(status); setMapping(mappingStatus); setSearchCoverage(coverage); setActiveId(status.providerId); setMessage(status.migrationNotice ?? status.summary) }).catch((reason: unknown) => { if (active) setMessage(reason instanceof Error ? reason.message : '資料狀態讀取失敗。') }); return () => { active = false } }, [])
  const select = async (id: ProviderId) => { if (!repositoryHub.selectProvider(id)) { setMessage('此資料來源尚未啟用。'); return }; setLoading(true); setActiveId(id); repositoryHub.industrySnapshots.clearCache(); repositoryHub.industryMapping.clearCache(); try { const status = await loadPlatform(true); setMessage(id === 'twse' ? status.summary : '已明確切換為 Mock；公開測試模式會持續顯示 Mock 標示。') } catch (reason) { setMessage(reason instanceof Error ? reason.message : '資料來源切換失敗；可回到 Mock 繼續使用。') } finally { setLoading(false) } }
  return <div className="space-y-8">
    <SectionHeader eyebrow="DATA SETTINGS · GULI v1.1.0-beta.2" title="資料來源設定" description="公開測試模式會分開揭露 Official、Derived、Mock、Fallback、Stale 與 Missing。"/>
    <Card title="公開測試模式" eyebrow="BETA DATA GUARD"><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><ShieldCheck size={20} className="mt-1 shrink-0 text-brand-300"/><div><p className="font-medium text-white">Mock 不得偽裝為真實行情</p><p className="mt-1 text-sm leading-6 text-slate-400">預設啟用；缺資料顯示尚未取得，核心頁面保留資料可信度與免責提示。</p></div></div><button type="button" role="switch" aria-label="公開測試模式" aria-checked={publicBetaMode} onClick={() => setPublicBetaMode(!publicBetaMode)} className={`relative h-11 w-20 shrink-0 rounded-full border transition-colors ${publicBetaMode ? 'border-brand-400/30 bg-brand-400/20' : 'border-white/10 bg-white/[.04]'}`}><span className={`absolute top-1.5 h-8 w-8 rounded-full bg-white transition-transform ${publicBetaMode ? 'translate-x-10' : 'translate-x-1.5'}`}/></button></div></Card>
    {platform?.canSwitchToTwse && <Card className="border-amber-300/20" title="目前仍使用 Mock 市場資料" eyebrow="ACTION REQUIRED"><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-start gap-2 text-sm leading-6 text-amber-100/90"><AlertTriangle size={17} className="mt-1 shrink-0"/>TWSE JSON 可用時，可切換至官方市場資料。</p><Button onClick={() => void select('twse')} disabled={loading}>切換至 TWSE 官方資料</Button></div></Card>}
    <Card title="市場總覽資料來源" eyebrow="PROVIDERS"><div className="grid gap-4 p-5 sm:p-6 lg:grid-cols-2">{providerFactory.list().map((provider) => <article key={provider.id} className={`rounded-2xl border p-5 ${activeId === provider.id ? 'border-brand-400/35 bg-brand-400/[.045]' : 'border-[var(--border-subtle)] bg-white/[.015]'}`}><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><Database size={20} className="mt-1 shrink-0 text-slate-400"/><div><h3 className="text-lg font-semibold text-white">{provider.name}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{provider.description}</p></div></div><span className="text-xs text-slate-400">{provider.enabled ? '可用' : '未啟用'}</span></div><Button className="mt-5 w-full" disabled={loading || !provider.enabled || activeId === provider.id} onClick={() => void select(provider.id)} icon={activeId === provider.id ? <Check size={17}/> : provider.enabled ? <Database size={17}/> : <LockKeyhole size={17}/>}>{activeId === provider.id ? '目前使用' : provider.enabled ? '切換' : '尚未開放'}</Button></article>)}</div><p className="border-t border-[var(--border-subtle)] px-5 py-4 text-sm leading-6 text-slate-400">{message}</p></Card>
    <Card title="資料覆蓋狀態" eyebrow="PROVENANCE"><div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-5"><Metric label="市場" value={platform?.market ?? '讀取中'}/><Metric label="個股" value={platform?.stocks ?? '讀取中'}/><Metric label="法人" value={platform?.institutions ?? '讀取中'}/><Metric label="產業" value={platform?.industry ?? '讀取中'}/><Metric label="產業覆蓋" value={mapping ? `${mapping.mappedStocks}/${mapping.totalStocks} · ${mapping.coverageRate}%` : '讀取中'}/></div><div className="flex flex-wrap gap-3 border-t border-white/[.05] p-5"><Button onClick={() => navigate('/data-status/stocks')}>個股資料狀態</Button><Button variant="ghost" onClick={() => navigate('/data-coverage')}>資料覆蓋率</Button></div></Card>
    <Card title="智慧搜尋資料覆蓋" eyebrow="LIVE REPOSITORY COVERAGE"><div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-5"><Metric label="上市行情" value={searchCoverage ? `${searchCoverage.officialStocks.toLocaleString()} / ${searchCoverage.totalStocks.toLocaleString()}` : '讀取中'}/><Metric label="歷史行情" value={searchCoverage ? `${searchCoverage.historyStocks.toLocaleString()} / ${searchCoverage.totalStocks.toLocaleString()}` : '讀取中'}/><Metric label="Technical" value={searchCoverage ? searchCoverage.technicalStocks.toLocaleString() : '讀取中'}/><Metric label="Decision" value={searchCoverage ? searchCoverage.decisionStocks.toLocaleString() : '讀取中'}/><Metric label="Snapshot" value={searchCoverage ? searchCoverage.snapshotStocks.toLocaleString() : '讀取中'}/></div><p className="border-t border-white/[.05] px-5 py-4 text-sm text-slate-400">數量由 SearchRepository 啟動時的實際索引計算，不使用寫死值；未覆蓋項目在搜尋預覽中顯示「Waiting」。</p></Card>
    <Card title="版本與發布流程" eyebrow="SYSTEM"><div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-4"><Metric label="GULI" value="v1.1.0-beta.2"/><Metric label="搜尋" value="Smart Search Center"/><Metric label="GitHub Pages" value="Actions Artifact Deployment"/><Metric label="Data Updates" value="Pull Request Workflow"/></div></Card>
    <Card title="資料免責聲明" eyebrow="INFORMATION ONLY"><div className="p-5 text-sm leading-7 text-slate-400">行情與法人資料為盤後資訊；市場情緒、Technical、Decision、Snapshot 與產業強度為固定規則推導。缺值不以 0 補入。本平台僅供資訊參考，不構成投資建議、買賣邀約或獲利保證。</div></Card>
  </div>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[.06] p-4"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-base font-medium text-white">{value}</p></div> }
