import { ChevronLeft, ChevronRight, Download, Filter, Search, Settings2 } from 'lucide-react'
import { cloneElement, useEffect, useMemo, useState, type ReactElement } from 'react'
import { ScreenerQuickDrawer } from '../components/screener/ScreenerQuickDrawer'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { DataTable, NumericCell } from '../components/ui/DataTable'
import { Disclaimer } from '../components/ui/Disclaimer'
import { Drawer } from '../components/ui/Drawer'
import { LoadingState } from '../components/ui/LoadingState'
import { SectionHeader } from '../components/ui/SectionHeader'
import { Select } from '../components/ui/Select'
import { repositoryHub } from '../repositories/RepositoryHub'
import { filterScreenerResults, searchScreenerResults } from '../services/screener/ScreenerFilterService'
import { screenerPresets } from '../services/screener/ScreenerPresetService'
import { paginateScreenerResults, rankScreenerResults, type ScreenerSortKey } from '../services/screener/ScreenerRankingService'
import { exportScreenerCsv } from '../services/screener/ScreenerSummaryService'
import type { ScreenerDataset, ScreenerFilters, ScreenerPresetId, ScreenerResult } from '../types/screener'

export function SmartScreener() {
  const [dataset, setDataset] = useState<ScreenerDataset | null>(null)
  const [loadState, setLoadState] = useState<'loading' | 'success' | 'error'>('loading')
  const [preset, setPreset] = useState<ScreenerPresetId>('strong-trend')
  const [query, setQuery] = useState('')
  const [sortKey, setSortKey] = useState<ScreenerSortKey>('technicalScore')
  const [page, setPage] = useState(1)
  const [filters, setFilters] = useState<ScreenerFilters>({})
  const [filterOpen, setFilterOpen] = useState(false)
  const [columnsOpen, setColumnsOpen] = useState(false)
  const [selected, setSelected] = useState<ScreenerResult | null>(null)
  const [showInstitution, setShowInstitution] = useState(true)
  useEffect(() => { let active = true; void repositoryHub.screener.getDataset().then((value) => { if (active) { setDataset(value); setLoadState('success') } }).catch(() => { if (active) setLoadState('error') }); return () => { active = false } }, [])
  const visible = useMemo(() => { if (!dataset) return []; const presetRows = dataset.results.filter((row) => row.presetId === preset && row.matched); return rankScreenerResults(filterScreenerResults(searchScreenerResults(presetRows, query), filters), sortKey) }, [dataset, filters, preset, query, sortKey])
  const paged = useMemo(() => paginateScreenerResults(visible, page, 25), [page, visible])
  useEffect(() => setPage(1), [filters, preset, query, sortKey])
  const downloadCsv = () => { const blob = new Blob([`\uFEFF${exportScreenerCsv(visible)}`], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `guli-screener-${dataset?.tradeDate ?? 'latest'}.csv`; link.click(); URL.revokeObjectURL(url) }
  return <div className="min-w-0 space-y-6">
    <SectionHeader eyebrow="FULL-MARKET TECHNICAL COVERAGE" title="智慧選股中心" description="只分析目前實際歷史行情覆蓋樣本；所有結果由固定規則產生，可解釋、可追溯、可重現。" action={<Button onClick={downloadCsv} disabled={!visible.length} icon={<Download size={16}/>}>匯出 CSV</Button>}/>
    {loadState === 'loading' && <Card><LoadingState rows={8}/></Card>}
    {loadState === 'error' && <Card state="error"><div className="p-6"><p className="text-base text-amber-300">選股索引尚未取得。</p><p className="mt-2 text-sm text-slate-500">請執行 npm run technical:index:generate 與 npm run screener:generate。</p></div></Card>}
    {dataset && <>
      <section className="grid grid-cols-2 gap-3 xl:grid-cols-6"><Summary label="可分析股票" value={dataset.sampleCount}/><Summary label="完整 250 日" value={dataset.complete250Count}/><Summary label="今日符合" value={visible.length}/><Summary label="高風險" value={dataset.highRiskCount}/><Summary label="資料交易日" value={dataset.tradeDate ?? '—'} small/><Summary label="產生時間" value={new Date(dataset.generatedAt).toLocaleString('zh-TW')} small/></section>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="預設選股策略">{dataset.presets.map((summary) => <button type="button" key={summary.presetId} onClick={() => setPreset(summary.presetId)} className={`min-h-32 rounded-xl border p-4 text-left transition ${preset === summary.presetId ? 'border-brand-400/40 bg-brand-400/[.06]' : 'border-white/[.07] bg-white/[.02] hover:border-white/[.14]'}`}><div className="flex items-start justify-between gap-2"><h2 className="text-sm font-semibold text-white">{summary.name}</h2><Badge tone={summary.presetId === 'high-risk-warning' ? 'warning' : 'brand'}>{summary.matchedCount}</Badge></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{summary.description}</p><p className="mono mt-3 text-xs text-slate-400">Tech {summary.averageTechnicalScore ?? '—'} · Conf {summary.averageConfidence ?? '—'}%</p></button>)}</section>
      <Card title="選股結果" eyebrow={`${screenerPresets.find((item) => item.id === preset)?.name ?? preset} · ${visible.length} 檔`} action={<div className="flex gap-1"><Button variant="ghost" onClick={() => setFilterOpen(true)} icon={<Filter size={16}/>}>篩選</Button><Button variant="ghost" onClick={() => setColumnsOpen((value) => !value)} icon={<Settings2 size={16}/>}>欄位</Button></div>}>
        <div className="flex flex-col gap-3 border-b border-white/[.06] p-4 sm:flex-row sm:items-center"><label className="relative flex-1"><span className="sr-only">搜尋代號、名稱或規則</span><Search size={16} className="absolute left-3 top-3.5 text-slate-500"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋代號、名稱或標籤" className="h-11 w-full rounded-xl border border-white/[.08] bg-[#0d1317] pl-10 pr-3 text-sm text-white outline-none focus:border-brand-400/40"/></label><Select value={sortKey} onChange={(event) => setSortKey(event.target.value as ScreenerSortKey)} aria-label="排序"><option value="technicalScore">Technical Score</option><option value="decisionScore">Decision</option><option value="confidence">Confidence</option><option value="changePercent">今日漲跌</option><option value="volumeRatio">量比</option><option value="riskLevel">風險</option></Select></div>
        {columnsOpen && <div className="border-b border-white/[.06] px-5 py-3"><label className="flex min-h-11 items-center gap-3 text-sm text-slate-300"><input type="checkbox" checked={showInstitution} onChange={(event) => setShowInstitution(event.target.checked)}/>顯示法人欄位</label></div>}
        {!visible.length ? <div className="p-10 text-center"><p className="text-base text-slate-300">目前實際樣本沒有符合此條件的股票。</p><p className="mt-2 text-sm text-slate-600">可切換策略或調整篩選條件；空結果不是錯誤。</p></div> : <><div className="hidden md:block"><DataTable minWidth={1180}><thead><tr>{['排名','股票','現價／漲跌','Technical','Decision','Confidence','RSI','MACD','量比','MA20',...(showInstitution?['法人']:[]),'風險','主要理由','更新'].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{paged.rows.map((row) => <tr key={row.symbol} onClick={() => setSelected(row)} className="cursor-pointer"><NumericCell>{row.rank}</NumericCell><td><p className="font-medium text-white">{row.symbol} {row.name}</p></td><NumericCell>{row.close ?? '—'}<span className={`ml-2 ${Number(row.changePercent) >= 0 ? 'text-red-300' : 'text-emerald-300'}`}>{row.changePercent?.toFixed(2) ?? '—'}%</span></NumericCell><NumericCell>{row.technicalScore?.toFixed(1) ?? '—'}</NumericCell><NumericCell>{row.decisionScore?.toFixed(1) ?? '—'}</NumericCell><NumericCell>{row.confidence}%</NumericCell><NumericCell>{row.rsi14?.toFixed(1) ?? '—'}</NumericCell><NumericCell>{row.macdHistogram?.toFixed(3) ?? '—'}</NumericCell><NumericCell>{row.volumeRatio?.toFixed(2) ?? '—'}</NumericCell><td>{row.aboveMa20 === null ? '—' : row.aboveMa20 ? '站上' : '跌破'}</td>{showInstitution && <NumericCell>{row.institutionalNet?.toLocaleString('zh-TW') ?? '—'}</NumericCell>}<td><Badge tone={row.riskLevel === 'high' ? 'warning' : row.riskLevel === 'medium' ? 'info' : 'brand'}>{row.riskLevel}</Badge></td><td className="max-w-64 truncate text-xs text-slate-400">{row.reasons[0]}</td><td className="text-xs text-slate-500">{row.tradeDate}</td></tr>)}</tbody></DataTable></div><div className="grid gap-3 p-4 md:hidden">{paged.rows.map((row) => <button type="button" key={row.symbol} onClick={() => setSelected(row)} className="min-h-44 rounded-xl border border-white/[.07] p-4 text-left"><div className="flex justify-between"><span className="font-semibold text-white">#{row.rank} · {row.symbol} {row.name}</span><Badge tone={row.riskLevel === 'high' ? 'warning' : 'brand'}>{row.riskLevel}</Badge></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><Metric label="Technical" value={row.technicalScore?.toFixed(1) ?? '—'}/><Metric label="Decision" value={row.decisionScore?.toFixed(1) ?? '—'}/><Metric label="Confidence" value={`${row.confidence}%`}/></div><p className="mt-4 text-xs leading-5 text-slate-400">{row.reasons[0]}</p></button>)}</div></>}
        <footer className="flex items-center justify-between border-t border-white/[.06] px-4 py-3"><span className="text-xs text-slate-500">第 {paged.page} / {paged.totalPages} 頁 · 每頁 25 筆</span><div className="flex gap-2"><Button size="sm" variant="ghost" disabled={paged.page <= 1} onClick={() => setPage((value) => value - 1)} aria-label="上一頁"><ChevronLeft size={17}/></Button><Button size="sm" variant="ghost" disabled={paged.page >= paged.totalPages} onClick={() => setPage((value) => value + 1)} aria-label="下一頁"><ChevronRight size={17}/></Button></div></footer>
      </Card><Disclaimer>{`目前僅分析實際技術索引涵蓋的 ${dataset.sampleCount} 檔，不代表全市場；選股結果不構成投資建議。`}</Disclaimer>
    </>}
    <Drawer open={filterOpen} onClose={() => setFilterOpen(false)} title="自訂篩選器"><FilterForm filters={filters} onChange={setFilters} onClose={() => setFilterOpen(false)}/></Drawer>
    <ScreenerQuickDrawer row={selected} onClose={() => setSelected(null)}/>
  </div>
}

function Summary({ label, value, small = false }: { label: string; value: string | number; small?: boolean }) { return <Card><div className="p-4"><p className="text-xs text-slate-500">{label}</p><p className={`mono mt-2 text-white ${small ? 'text-sm' : 'text-2xl'}`}>{value}</p></div></Card> }
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-slate-600">{label}</p><p className="mono mt-1 text-sm text-white">{value}</p></div> }
function FilterForm({ filters, onChange, onClose }: { filters: ScreenerFilters; onChange: (value: ScreenerFilters) => void; onClose: () => void }) { const number = (key: keyof ScreenerFilters, value: string) => onChange({ ...filters, [key]: value === '' ? undefined : Number(value) }); return <div className="space-y-5 p-5 sm:p-6"><div className="grid grid-cols-2 gap-4"><Field label="Technical 最低"><input type="number" value={filters.technicalScoreMin ?? ''} onChange={(event) => number('technicalScoreMin', event.target.value)}/></Field><Field label="Decision 最低"><input type="number" value={filters.decisionScoreMin ?? ''} onChange={(event) => number('decisionScoreMin', event.target.value)}/></Field><Field label="RSI 最低"><input type="number" value={filters.rsiMin ?? ''} onChange={(event) => number('rsiMin', event.target.value)}/></Field><Field label="RSI 最高"><input type="number" value={filters.rsiMax ?? ''} onChange={(event) => number('rsiMax', event.target.value)}/></Field><Field label="量比最低"><input type="number" step="0.1" value={filters.volumeRatioMin ?? ''} onChange={(event) => number('volumeRatioMin', event.target.value)}/></Field><Field label="波動率最高"><input type="number" value={filters.volatilityMax ?? ''} onChange={(event) => number('volatilityMax', event.target.value)}/></Field><Field label="20 日報酬最低"><input type="number" value={filters.return20Min ?? ''} onChange={(event) => number('return20Min', event.target.value)}/></Field><Field label="資料完整日數"><input type="number" value={filters.completenessMin ?? ''} onChange={(event) => number('completenessMin', event.target.value)}/></Field></div><Toggle label="收盤站上 MA20" checked={filters.aboveMa20 === true} onChange={(checked) => onChange({ ...filters, aboveMa20: checked ? true : undefined })}/><Toggle label="只使用完整官方來源" checked={filters.officialOnly === true} onChange={(checked) => onChange({ ...filters, officialOnly: checked || undefined })}/><Toggle label="排除高風險" checked={filters.excludeHighRisk === true} onChange={(checked) => onChange({ ...filters, excludeHighRisk: checked || undefined })}/><div className="flex gap-3"><Button className="flex-1" onClick={() => onChange({})}>重設</Button><Button className="flex-1" variant="primary" onClick={onClose}>套用條件</Button></div></div> }
function Field({ label, children }: { label: string; children: ReactElement<{ className?: string }> }) { return <label className="text-xs text-slate-400">{label}{cloneElement(children, { className: 'mt-2 h-11 w-full rounded-xl border border-white/[.08] bg-[#0d1317] px-3 text-sm text-white outline-none' })}</label> }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="flex min-h-11 items-center gap-3 text-sm text-slate-300"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)}/>{label}</label> }
