import { describe,expect,it } from 'vitest'
import { createHeatmapDataset } from '../generate-market-heatmap.mjs'
import { buildSnapshotIndustries } from '../generate-industry-snapshot.mjs'

const mapping={schemaVersion:'1.0',market:'TWSE',source:'TWSE',sourceUrl:'https://openapi.twse.com.tw/v1/opendata/t187ap03_L',fetchedAt:'2026-07-20T08:00:00.000Z',effectiveDate:'2026-07-19',totalRecords:2,stockRecords:2,excludedRecords:0,mappedStockCount:1,unmappedStockCount:1,status:'partial',warnings:[],industries:[{industryCode:'24',industryName:'半導體業',stockCount:1,source:'TWSE',status:'official'}],stocks:[{symbol:'2330',name:'台積電',market:'TWSE',instrumentType:'stock',industryCode:'24',industryName:'半導體業',source:'TWSE',status:'official',updatedAt:'2026-07-20T08:00:00.000Z'},{symbol:'2317',name:'鴻海',market:'TWSE',instrumentType:'stock',industryCode:null,industryName:null,source:'TWSE',status:'missing',updatedAt:'2026-07-20T08:00:00.000Z'}]}
const stocks={tradeDate:'2026-07-18',fetchedAt:'2026-07-18T10:00:00.000Z',records:[{symbol:'2330',name:'台積電',market:'TWSE',instrumentType:'stock',tradeValue:1000,tradeVolume:100,close:100,change:1,tradeDate:'2026-07-18'},{symbol:'2317',name:'鴻海',market:'TWSE',instrumentType:'stock',tradeValue:500,tradeVolume:50,close:50,change:-1,tradeDate:'2026-07-18'}]}
describe('official industry generator integration',()=>{
  it('keeps every common stock in the Heatmap',()=>{const result=createHeatmapDataset({stocksDataset:stocks,technicalDataset:{records:[]},screenerDataset:{results:[]},decisionDataset:{},industryMappingDataset:mapping,industryInput:{industries:[]}});expect(result.stocks).toHaveLength(2)})
  it('counts exact official and unmapped records',()=>{const result=createHeatmapDataset({stocksDataset:stocks,technicalDataset:{records:[]},screenerDataset:{results:[]},decisionDataset:{},industryMappingDataset:mapping,industryInput:{industries:[]}});expect(result).toMatchObject({officialMappedStockCount:1,derivedMappedStockCount:0,unmappedStockCount:1,officialCoverageRate:50})})
  it('labels the official Heatmap stock with TWSE industry',()=>{const result=createHeatmapDataset({stocksDataset:stocks,technicalDataset:{records:[]},screenerDataset:{results:[]},decisionDataset:{},industryMappingDataset:mapping,industryInput:{industries:[]}});expect(result.stocks.find((row)=>row.symbol==='2330')).toMatchObject({industryName:'半導體業',mappingStatus:'official'})})
  it('keeps an unknown Heatmap stock unclassified',()=>{const result=createHeatmapDataset({stocksDataset:stocks,technicalDataset:{records:[]},screenerDataset:{results:[]},decisionDataset:{},industryMappingDataset:mapping,industryInput:{industries:[]}});expect(result.stocks.find((row)=>row.symbol==='2317')).toMatchObject({industryName:'未分類',mappingStatus:'missing'})})
  it('uses an explicit derived group only after official mapping',()=>{const input={industries:[{id:'ai',name:'AI 伺服器',stocks:[{symbol:'2317'}]}]};const result=createHeatmapDataset({stocksDataset:stocks,technicalDataset:{records:[]},screenerDataset:{results:[]},decisionDataset:{},industryMappingDataset:mapping,industryInput:input});expect(result.stocks.find((row)=>row.symbol==='2317')).toMatchObject({industryName:'AI 伺服器',mappingStatus:'derived'});expect(result.stocks.find((row)=>row.symbol==='2330')?.industryName).toBe('半導體業')})
  it('does not fabricate Technical and Decision averages',()=>{const result=buildSnapshotIndustries({stocksDataset:stocks,mappingDataset:mapping,institutionalDataset:{records:[]},technicalDataset:{records:[]},screenerDataset:{results:[]},marketReturn:0,warnings:[]});expect(result.find((row)=>row.industryId==='24')).toMatchObject({technicalAverage:null,technicalSampleCount:0,decisionAverage:null,decisionSampleCount:0})})
  it('aggregates constituent count and breadth from official members',()=>{const result=buildSnapshotIndustries({stocksDataset:stocks,mappingDataset:mapping,institutionalDataset:{records:[]},technicalDataset:{records:[]},screenerDataset:{results:[]},marketReturn:0,warnings:[]});expect(result.find((row)=>row.industryId==='24')).toMatchObject({constituentCount:1,advanceCount:1,declineCount:0})})
  it('keeps the missing member in the unclassified snapshot',()=>{const result=buildSnapshotIndustries({stocksDataset:stocks,mappingDataset:mapping,institutionalDataset:{records:[]},technicalDataset:{records:[]},screenerDataset:{results:[]},marketReturn:0,warnings:[]});expect(result.find((row)=>row.industryId==='unclassified')).toMatchObject({industryName:'未分類',constituentCount:1,dataStatus:'Partial'})})
})
