import { ArrowDown, ArrowUp, Building2, RefreshCw } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { repositoryHub } from '../../repositories/RepositoryHub'
import { getInstitutionalNetShares, toHundredMillionTWD, toLots } from '../../services/institutionalData/InstitutionalService'
import type { InstitutionalInvestorType, InstitutionalMarketTotals, OfficialStockInstitutionalRecord } from '../../types/officialInstitutionalData'
import { Badge } from '../ui/Badge'
import { Button } from '../ui/Button'
import { Card } from '../ui/Card'
import { EmptyState } from '../ui/EmptyState'
import { LoadingState } from '../ui/LoadingState'

const labels: Record<InstitutionalInvestorType, string> = { foreign: '外資及陸資', trust: '投信', dealer: '自營商', total: '三大法人合計' }
const amountText = (value: number | null) => { const result = toHundredMillionTWD(value); return result === null ? '尚未取得' : `${result > 0 ? '+' : ''}${result.toFixed(2)} 億元` }
export function InstitutionalOverview() {
  const [totals, setTotals] = useState<InstitutionalMarketTotals | null>(null)
  const [buy, setBuy] = useState<OfficialStockInstitutionalRecord[]>([])
  const [sell, setSell] = useState<OfficialStockInstitutionalRecord[]>([])
  const [type, setType] = useState<InstitutionalInvestorType>('total')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const load = useCallback(async (refresh = false) => { setLoading(true); setError(''); try { if (refresh) await repositoryHub.institutions.refresh(); const [nextTotals, nextBuy, nextSell] = await Promise.all([repositoryHub.institutions.getMarketTotals(), repositoryHub.institutions.getTopNetBuy(type, 10), repositoryHub.institutions.getTopNetSell(type, 10)]); setTotals(nextTotals); setBuy(nextBuy); setSell(nextSell); if (!nextTotals) setError('官方法人資料尚未取得。') } catch (cause) { setError(cause instanceof Error ? cause.message : '官方法人資料尚未取得。') } finally { setLoading(false) } }, [type])
  useEffect(() => { void load() }, [load])
  if (loading) return <Card title="三大法人盤後資料" eyebrow="TWSE OFFICIAL"><LoadingState rows={5}/></Card>
  return <section className="space-y-4" aria-label="TWSE 官方三大法人盤後資料"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-medium text-slate-200">三大法人盤後資料</p><p className="mt-1 text-[10px] text-slate-600">市場金額單位為新臺幣元，畫面換算億元；個股買賣超單位為股，畫面換算張。</p></div><div className="flex gap-2"><Badge tone="info">TWSE Official</Badge><Button variant="ghost" onClick={() => void load(true)} icon={<RefreshCw size={15}/>}>重新讀取</Button></div></div>{totals ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{(Object.keys(labels) as InstitutionalInvestorType[]).map((key) => { const item = totals[key]; const positive = (item.netAmount ?? 0) >= 0; return <Card key={key}><div className="p-4"><div className="flex items-center justify-between"><span className="text-xs text-slate-400">{labels[key]}</span><Badge tone="info">TWSE Official</Badge></div><p className={`mono mt-4 text-xl ${positive ? 'text-red-300' : 'text-emerald-300'}`}>{amountText(item.netAmount)}</p><div className="mt-4 grid grid-cols-2 gap-2 text-[10px] text-slate-500"><span>買進<br/><strong className="mono text-slate-300">{amountText(item.buyAmount)}</strong></span><span>賣出<br/><strong className="mono text-slate-300">{amountText(item.sellAmount)}</strong></span></div></div></Card> })}</div> : <Card><EmptyState title="官方法人資料尚未取得" description={error || '請稍後重新讀取網站內的靜態 JSON。'}/></Card>}<Card title="法人個股買賣超排行" eyebrow="TWSE T86 · SHARES"><div className="flex flex-wrap gap-2 border-b border-white/[.06] p-4">{(Object.keys(labels) as InstitutionalInvestorType[]).map((key) => <button key={key} type="button" onClick={() => setType(key)} className={`min-h-11 rounded-xl px-4 text-sm ${type === key ? 'bg-brand-400/10 text-brand-300' : 'text-slate-400 hover:bg-white/[.04]'}`}>{labels[key]}</button>)}</div><div className="grid lg:grid-cols-2"><Ranking title="買超 Top 10" rows={buy} type={type} direction="buy"/><Ranking title="賣超 Top 10" rows={sell} type={type} direction="sell"/></div></Card></section>
}
function Ranking({ title, rows, type, direction }: { title: string; rows: OfficialStockInstitutionalRecord[]; type: InstitutionalInvestorType; direction: 'buy' | 'sell' }) { const Icon = direction === 'buy' ? ArrowUp : ArrowDown; return <section className="border-white/[.06] p-4 first:border-b lg:first:border-b-0 lg:first:border-r"><h3 className="flex items-center gap-2 text-sm font-semibold text-white"><Icon size={16} className={direction === 'buy' ? 'text-red-300' : 'text-emerald-300'}/>{title}</h3><div className="mt-3 space-y-1">{rows.length ? rows.map((record, index) => { const value = toLots(getInstitutionalNetShares(record, type)); return <div key={record.symbol} className="flex min-h-10 items-center gap-3 rounded-lg px-2 text-xs hover:bg-white/[.025]"><span className="mono w-5 text-slate-600">{index + 1}</span><Building2 size={13} className="text-slate-600"/><span className="min-w-0 flex-1 truncate text-slate-300">{record.symbol} {record.name}</span><span className={`mono ${direction === 'buy' ? 'text-red-300' : 'text-emerald-300'}`}>{value === null ? '—' : `${value > 0 ? '+' : ''}${value.toLocaleString('zh-TW', { maximumFractionDigits: 0 })} 張`}</span></div> }) : <p className="py-8 text-center text-xs text-slate-600">尚未取得</p>}</div></section> }
