import { ArrowDownRight, ArrowUpRight, CloudRain, Info, Sun } from 'lucide-react'
import { marketRepository } from '../../services/dataRepository'
import { Card } from '../ui/Card'
import { Disclaimer } from '../ui/Disclaimer'
import { Tooltip } from '../ui/Tooltip'

const mockMarketTemperature = marketRepository.getOverview().temperature

const status=(score:number)=>score<=20?'極弱':score<=40?'偏弱':score<=60?'中性':score<=80?'偏強':'極強'

export function MarketTemperature() {
  const data=mockMarketTemperature; const rotation=-90+(data.score/100)*180; const Weather=data.weather==='晴天'?Sun:CloudRain
  return <Card className="h-full overflow-hidden" title="市場溫度" eyebrow="Market Temperature" action={<Tooltip label="綜合法人、量能、漲跌家數與動能計算"><button type="button" className="grid h-10 w-10 place-items-center text-slate-600 hover:text-slate-300" aria-label="市場溫度說明"><Info size={15}/></button></Tooltip>}><div className="px-5 pt-5"><div className="relative mx-auto h-[154px] w-[290px] max-w-full overflow-hidden"><div className="absolute left-1/2 top-5 h-[260px] w-[260px] -translate-x-1/2 rounded-full bg-[conic-gradient(from_270deg,#38b987_0deg,#e5b34d_90deg,#ef6a78_180deg,rgba(255,255,255,.06)_180deg)] p-[13px]"><div className="h-full w-full rounded-full bg-[var(--bg-card)]"/></div><div className="absolute bottom-0 left-1/2 h-[96px] w-0.5 origin-bottom bg-white/75 transition-transform duration-300" style={{transform:`rotate(${rotation}deg)`}}/><div className="absolute bottom-1 left-1/2 -translate-x-1/2 text-center"><p className="mono text-4xl font-medium text-white">{data.score}</p><p className="mt-1 text-xs font-semibold text-brand-300">{status(data.score)}</p></div><span className="absolute bottom-1 left-2 text-[9px] text-slate-700">極弱</span><span className="absolute bottom-1 right-2 text-[9px] text-slate-700">極強</span></div><div className="mt-3 flex items-center justify-center gap-4"><span className="flex items-center gap-1.5 text-[11px] text-slate-300"><Weather size={15} className="text-amber-300"/>{data.weather}</span><span className="h-4 w-px bg-[var(--border-subtle)]"/><span className="flex items-center gap-1 text-[10px] text-slate-500"><ArrowUpRight size={13} className="text-brand-400"/>較昨日 +6</span></div></div><div className="grid grid-cols-2 gap-2 p-5">{data.reasons.map((reason,index)=>{const up=index!==1; const Direction=up?ArrowUpRight:ArrowDownRight; return <div key={reason.label} className="rounded-xl border border-[var(--border-subtle)] bg-white/[.015] p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-slate-500">{reason.label}</span><Direction size={12} className={up?'text-brand-400':'text-amber-400'}/></div><div className="mt-2 flex items-end justify-between"><span className="mono text-lg text-white">{reason.value}</span><span className="text-[8px] text-slate-600">{up?'改善':'降溫'}</span></div></div>})}</div><div className="px-5 pb-5"><Disclaimer>市場溫度僅反映當日數據狀態，不代表未來漲跌。</Disclaimer></div></Card>
}
