import { AlertTriangle, ArrowRight, CircleMinus, TrendingUp } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { marketRepository } from '../../services/dataRepository'
import { Badge } from '../ui/Badge'
import { Card } from '../ui/Card'

export function MarketSummary() {
  const mockSignals = marketRepository.getSignals()
  const navigate=useNavigate()
  return <Card className="h-full" title="今日市場摘要" eyebrow="GULI Market Brief" action={<span className="flex items-center gap-2 text-[9px] text-slate-600"><span className="live-dot h-1.5 w-1.5 rounded-full bg-brand-400"/>5 則重點</span>}><div className="grid divide-y divide-[var(--border-subtle)]">{mockSignals.map((signal)=>{const warning=signal.type==='風險'; const neutral=signal.type==='產業'; const Icon=warning?AlertTriangle:neutral?CircleMinus:TrendingUp; const tone=warning?'warning':neutral?'neutral':'brand'; return <article key={signal.id} className={`relative grid gap-3 px-5 py-3.5 transition-colors hover:bg-white/[.018] sm:grid-cols-[auto_1fr_auto] sm:items-center ${warning?'border-l-2 border-l-amber-400/70':neutral?'border-l-2 border-l-blue-400/50':'border-l-2 border-l-brand-400/60'}`}><div className={`grid h-8 w-8 place-items-center rounded-lg ${warning?'bg-amber-400/10 text-amber-300':neutral?'bg-blue-400/10 text-blue-300':'bg-brand-400/10 text-brand-300'}`}><Icon size={14}/></div><div className="min-w-0"><div className="flex items-center gap-2"><Badge tone={tone}>{signal.type}</Badge><span className="truncate text-xs font-medium text-slate-200">{signal.title}</span></div><p className="mt-1 truncate text-[10px] text-slate-600">{signal.description}</p><p className="mt-1 text-[9px] text-slate-700">相關：{signal.industries.join('、')} · 方向：{warning?'警示':neutral?'中性':'正向'}</p></div><div className="flex items-center justify-between gap-4 sm:justify-end"><div className="text-right"><p className="mono text-[10px] text-slate-300">{signal.intensity}</p><div className="mt-1 h-1 w-14 overflow-hidden rounded-full bg-white/[.05]"><div className={`h-full ${warning?'bg-amber-400':'bg-brand-400'}`} style={{width:`${signal.intensity}%`}}/></div></div><button type="button" onClick={()=>navigate(`/market-focus?signal=${signal.id}`)} className="grid h-10 w-10 place-items-center rounded-lg text-slate-600 hover:bg-white/[.04] hover:text-white" aria-label={`查看${signal.title}`}><ArrowRight size={14}/></button></div></article>})}</div></Card>
}
