import { Award } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { marketRepository } from '../../services/dataRepository'
import { Card } from '../ui/Card'
import { Tabs } from '../ui/Tabs'

type RankingTab='strong'|'weak'|'institution'|'volume'

export function MarketRanking() {
  const mockIndustries = marketRepository.getIndustries(); const mockStocks = marketRepository.getStocks()
  const [tab,setTab]=useState<RankingTab>('strong'); const navigate=useNavigate()
  const items=useMemo(()=>{if(tab==='strong')return [...mockIndustries].sort((a,b)=>b.changePercent-a.changePercent).slice(0,6).map((item)=>({id:item.id,name:item.name,value:item.changePercent,display:`${item.changePercent>0?'+':''}${item.changePercent.toFixed(2)}%`,route:`/capital-flow?industry=${encodeURIComponent(item.name)}`,up:item.changePercent>=0})); if(tab==='weak')return [...mockIndustries].sort((a,b)=>a.changePercent-b.changePercent).slice(0,6).map((item)=>({id:item.id,name:item.name,value:Math.abs(item.changePercent),display:`${item.changePercent>0?'+':''}${item.changePercent.toFixed(2)}%`,route:`/capital-flow?industry=${encodeURIComponent(item.name)}`,up:item.changePercent>=0})); if(tab==='institution')return [...mockStocks].sort((a,b)=>b.institutions.total-a.institutions.total).slice(0,6).map((item)=>({id:item.symbol,name:`${item.symbol} ${item.name}`,value:Math.abs(item.institutions.total),display:`${item.institutions.total.toFixed(1)} 百萬`,route:`/stock/${item.symbol}`,up:item.institutions.total>=0})); return [...mockStocks].sort((a,b)=>b.volume-a.volume).slice(0,6).map((item)=>({id:item.symbol,name:`${item.symbol} ${item.name}`,value:item.volume,display:`${(item.volume/1000).toFixed(1)}K 張`,route:`/stock/${item.symbol}`,up:item.changePercent>=0}))},[tab])
  const max=Math.max(...items.map((item)=>item.value),1)
  return <Card className="h-full" title="市場排行榜" eyebrow="Market Ranking"><div className="overflow-x-auto border-b border-[var(--border-subtle)] p-3"><Tabs value={tab} onChange={setTab} options={[{value:'strong',label:'強勢產業'},{value:'weak',label:'弱勢產業'},{value:'institution',label:'法人買超'},{value:'volume',label:'量能異常'}]}/></div><div key={tab} className="page-enter p-3">{items.map((item,index)=><button type="button" key={item.id} onClick={()=>navigate(item.route)} className="group grid min-h-[58px] w-full grid-cols-[28px_minmax(0,1fr)_auto] items-center gap-2 rounded-xl px-2 text-left hover:bg-white/[.025]"><span className={`mono grid h-6 w-6 place-items-center rounded-md text-[9px] ${index<3?'bg-brand-400/[.08] text-brand-300':'text-slate-700'}`}>{index<3?<Award size={12}/>:String(index+1).padStart(2,'0')}</span><div className="min-w-0"><p className="truncate text-[11px] text-slate-300 group-hover:text-white">{item.name}</p><div className="mt-2 flex h-3 items-end gap-0.5" aria-hidden="true">{[.38,.56,.44,.72,.62,.88,.78].map((ratio,i)=><span key={i} className={`w-1 rounded-t ${item.up?'bg-red-400/35':'bg-emerald-400/35'}`} style={{height:`${Math.max(2,ratio*10*(1+index*.03))}px`}}/>)}</div></div><div className="text-right"><span className={`mono text-[10px] ${item.up?'text-red-400':'text-emerald-400'}`}>{item.display}</span><div className="mt-1.5 h-0.5 w-14 overflow-hidden rounded-full bg-white/[.04]"><div className={item.up?'h-full bg-red-400/60':'h-full bg-emerald-400/60'} style={{width:`${Math.max(8,item.value/max*100)}%`}}/></div></div></button>)}</div></Card>
}
