import { ArrowRight, ShieldAlert } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { repositoryHub } from '../../repositories/RepositoryHub'
import type { StockSnapshotIndexItem } from '../../types/stockSnapshot'
import { Button } from '../ui/Button'
import { Card } from '../ui/Card'
import { LoadingState } from '../ui/LoadingState'
export function StockSnapshotPreview(){const navigate=useNavigate();const[groups,setGroups]=useState<{score:StockSnapshotIndexItem[];value:StockSnapshotIndexItem[];gainers:StockSnapshotIndexItem[];risk:number}|null>(null);useEffect(()=>{let active=true;Promise.all([repositoryHub.stockSnapshots.getTopStocks('snapshotScore',3),repositoryHub.stockSnapshots.getTopStocks('tradeValue',3),repositoryHub.stockSnapshots.getTopStocks('gainers',3),repositoryHub.stockSnapshots.getLatestIndex()]).then(([score,value,gainers,index])=>{if(active)setGroups({score,value,gainers,risk:index.records.filter((item)=>item.highRiskCount>0).length})});return()=>{active=false}},[]);return <Card title="官方個股快照" eyebrow="TWSE STOCK SNAPSHOT" action={<Button size="sm" variant="ghost" onClick={()=>navigate('/stock-snapshots')} icon={<ArrowRight size={13}/>}>查看完整排行</Button>}>{!groups?<LoadingState rows={3}/>:<div className="grid gap-4 p-5 lg:grid-cols-4"><List title="快照分數" rows={groups.score} value={(row)=>row.snapshotScore}/><List title="成交金額" rows={groups.value} value={(row)=>row.tradeValue===null?null:row.tradeValue/100_000_000} suffix=" 億"/><List title="單日漲幅" rows={groups.gainers} value={(row)=>row.changePercent} suffix="%"/><div className="rounded-xl border border-amber-400/15 bg-amber-400/[.03] p-4"><ShieldAlert size={18} className="text-amber-300"/><p className="mt-3 text-[10px] text-slate-500">含高風險規則股票數</p><p className="mono mt-2 text-2xl text-white">{groups.risk}</p><p className="mt-2 text-[9px] text-slate-600">僅反映當日官方價量衍生規則</p></div></div>}</Card>}
function List({title,rows,value,suffix=''}:{title:string;rows:StockSnapshotIndexItem[];value:(row:StockSnapshotIndexItem)=>number|null;suffix?:string}){const navigate=useNavigate();return <div><p className="mb-2 text-[10px] text-slate-500">{title}</p>{rows.map((row,index)=><button key={row.symbol} onClick={()=>navigate(`/stock/${row.symbol}`)} className="flex min-h-11 w-full items-center justify-between rounded-lg px-2 text-left hover:bg-white/[.035]"><span className="text-[11px] text-slate-300">{index+1}. {row.name} <span className="text-slate-600">{row.symbol}</span></span><span className="mono text-[10px] text-white">{value(row)?.toLocaleString('zh-TW',{maximumFractionDigits:2})??'—'}{suffix}</span></button>)}</div>}
