import { describe, expect, it, vi } from 'vitest'
import { IndustrySnapshotRepository } from '../IndustrySnapshotRepository'
import { IndustrySnapshotStorage, IndustrySnapshotStorageError } from '../../services/industrySnapshot/IndustrySnapshotStorage'
const snapshot={schemaVersion:'1.0',tradeDate:'2026-07-13',generatedAt:'2026-07-13T08:00:00.000Z',market:'TWSE',industries:[{industryId:'a',industryName:'A',rank:1,previousRank:null,rankChange:null,strengthScore:70,momentumScore:70,capitalFlowScore:70,breadthScore:70,relativeStrengthScore:70,riskScore:20,status:'偏強',direction:'flat',return1d:null,return5d:null,return20d:null,institutionalNetBuy:null,tradingAmount:null,advanceCount:null,declineCount:null,unchangedCount:null,leaderStocks:[],laggardStocks:[],risks:[],tags:[],sources:[]}],sources:[],warnings:[]}
const index={schemaVersion:'1.0',updatedAt:'2026-07-13T08:00:00.000Z',snapshots:[{tradeDate:'2026-07-13',path:'data/industry-history/2026-07-13.json',topIndustries:['A'],weakIndustries:[]}]}
describe('IndustrySnapshotRepository',()=>{
  it('reads the latest snapshot through storage',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify(snapshot),{status:200}));const repo=new IndustrySnapshotRepository(new IndustrySnapshotStorage(fetcher,'/guli/',1000));expect((await repo.getLatest()).tradeDate).toBe('2026-07-13')})
  it('does not fetch the same valid cache twice',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify(snapshot),{status:200}));const repo=new IndustrySnapshotRepository(new IndustrySnapshotStorage(fetcher,'/guli/',1000));await repo.getLatest();await repo.getLatest();expect(fetcher).toHaveBeenCalledTimes(1)})
  it('reads history and filters a single industry',async()=>{const fetcher=vi.fn(async(input:RequestInfo|URL)=>new Response(JSON.stringify(String(input).endsWith('index.json')?index:snapshot),{status:200}));const repo=new IndustrySnapshotRepository(new IndustrySnapshotStorage(fetcher,'/guli/',1000));expect((await repo.getIndustryHistory('a',5))).toHaveLength(1)})
  it('rejects incompatible schemas without returning invalid data',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({...snapshot,schemaVersion:'2.0'}),{status:200}));const repo=new IndustrySnapshotRepository(new IndustrySnapshotStorage(fetcher,'/guli/',1000));await expect(repo.getLatest()).rejects.toBeInstanceOf(IndustrySnapshotStorageError)})
})
