import { describe,expect,it,vi } from 'vitest'
import { TWSEIndustryMappingProvider } from '../../providers/TWSEIndustryMappingProvider'
import type { OfficialIndustryMappingDataset } from '../../types/officialIndustryMapping'
import { IndustryMappingRepository } from '../IndustryMappingRepository'

const dataset:OfficialIndustryMappingDataset={schemaVersion:'1.0',market:'TWSE',source:'TWSE',sourceUrl:'https://openapi.twse.com.tw/v1/opendata/t187ap03_L',fetchedAt:'2026-07-20T08:00:00.000Z',effectiveDate:'2026-07-19',totalRecords:2,stockRecords:2,excludedRecords:0,mappedStockCount:2,unmappedStockCount:0,status:'official',warnings:[],industries:[{industryCode:'24',industryName:'半導體業',stockCount:1,source:'TWSE',status:'official'},{industryCode:'25',industryName:'電腦及週邊設備業',stockCount:1,source:'TWSE',status:'official'}],stocks:[{symbol:'2330',name:'台積電',market:'TWSE',instrumentType:'stock',industryCode:'24',industryName:'半導體業',source:'TWSE',status:'official',updatedAt:'2026-07-20T08:00:00.000Z'},{symbol:'2317',name:'鴻海',market:'TWSE',instrumentType:'stock',industryCode:'25',industryName:'電腦及週邊設備業',source:'TWSE',status:'official',updatedAt:'2026-07-20T08:00:00.000Z'}]}
describe('TWSEIndustryMappingProvider and repository',()=>{
  it('uses the GitHub Pages base URL',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify(dataset)));await new TWSEIndustryMappingProvider(fetcher,'/guli/').getLatest();expect(String(fetcher.mock.calls[0][0])).toBe('/guli/data/twse-industries/latest.json')})
  it('does not re-read the same valid cache',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify(dataset)));const provider=new TWSEIndustryMappingProvider(fetcher,'/guli/',1000);await provider.getLatest();await provider.getLatest();expect(fetcher).toHaveBeenCalledTimes(1)})
  it('refresh bypasses the provider cache',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify(dataset)));const provider=new TWSEIndustryMappingProvider(fetcher,'/guli/',1000);await provider.getLatest();await provider.refresh();expect(fetcher).toHaveBeenCalledTimes(2)})
  it('returns a structured missing status',async()=>{const status=await new TWSEIndustryMappingProvider(async()=>new Response('',{status:404}),'/guli/').getStatus();expect(status).toMatchObject({available:false,status:'missing'})})
  it('gets a stock mapping by symbol',async()=>{const repo=new IndustryMappingRepository(new TWSEIndustryMappingProvider(async()=>new Response(JSON.stringify(dataset)),'/guli/'));expect((await repo.getBySymbol('2330'))?.industryName).toBe('半導體業')})
  it('returns null for an unknown symbol',async()=>{const repo=new IndustryMappingRepository(new TWSEIndustryMappingProvider(async()=>new Response(JSON.stringify(dataset)),'/guli/'));expect(await repo.getBySymbol('9999')).toBeNull()})
  it('filters stocks by official industry code',async()=>{const repo=new IndustryMappingRepository(new TWSEIndustryMappingProvider(async()=>new Response(JSON.stringify(dataset)),'/guli/'));expect((await repo.getStocksByIndustry('24')).map((row)=>row.symbol)).toEqual(['2330'])})
  it('calculates repository coverage from records',async()=>{const repo=new IndustryMappingRepository(new TWSEIndustryMappingProvider(async()=>new Response(JSON.stringify(dataset)),'/guli/'));expect(await repo.getCoverage()).toMatchObject({totalStocks:2,mappedStocks:2,coverageRate:100,industryCount:2})})
})
