import { describe, expect, it } from 'vitest'
import { generateTodayMarketNarrative, getOperationEnvironment } from '../TodayMarketNarrativeService'
import type { DecisionResult } from '../../../types/decision'
import type { IndustrySnapshot } from '../../../types/industrySnapshot'
import type { OfficialMarketOverview } from '../../../types/marketData'
import type { InstitutionalMarketTotals } from '../../../types/officialInstitutionalData'
import type { ScreenerDataset } from '../../../types/screener'

const market = (changePercent = 1, advanceCount = 700, declineCount = 300): OfficialMarketOverview => ({ schemaVersion: '2.0', market: 'TWSE', tradeDate: '2026-07-16', indexName: '發行量加權股價指數', indexValue: 24_000, change: changePercent * 240, changePercent, tradingAmount: 500_000_000_000, tradingVolume: 9_000_000_000, transactionCount: 1_000_000, advanceCount, declineCount, unchangedCount: 100, limitUpCount: null, limitDownCount: null, breadthSource: 'stock_day_all', tradingHistory: [{ tradeDate: '2026-07-15', indexValue: 23_900, tradingAmount: 400_000_000_000, tradingVolume: 8_000_000_000, transactionCount: 900_000 }, { tradeDate: '2026-07-16', indexValue: 24_000, tradingAmount: 500_000_000_000, tradingVolume: 9_000_000_000, transactionCount: 1_000_000 }], rankings: { tradingAmount: [], tradingVolume: [], gainers: [], losers: [] }, source: 'TWSE', fetchedAt: '2026-07-16T08:00:00.000Z', status: 'official', warnings: [] })
const institutions = (net: number): InstitutionalMarketTotals => ({ foreign: { buyAmount: 100, sellAmount: 100 - net, netAmount: net }, trust: { buyAmount: 20, sellAmount: 20, netAmount: 0 }, dealer: { buyAmount: 10, sellAmount: 10, netAmount: 0 }, total: { buyAmount: 130, sellAmount: 130 - net, netAmount: net } })
const decision = (direction: DecisionResult['direction']): DecisionResult => ({ entityType: 'market', entityId: 'TWSE', entityName: '市場', tradeDate: '2026-07-16', score: direction === 'bullish' ? 75 : direction === 'bearish' ? 30 : 52, label: '中性', direction, confidence: 80, summary: '', factors: [], risks: [], trace: { formulaVersion: 'decision-v1.0', totalPositiveContribution: 0, totalNegativeContribution: 0, totalContribution: 0, availableWeight: 1, missingWeight: 0, normalizationApplied: false, calculationSteps: [] }, sources: [], warnings: [] })
const industries = (): IndustrySnapshot => ({ schemaVersion: '1.0', tradeDate: '2026-07-16', generatedAt: '2026-07-16T08:00:00Z', market: 'TWSE', industries: [{ industryId: 'semi', industryName: '半導體', rank: 1, previousRank: 1, rankChange: 0, strengthScore: 80, momentumScore: 80, capitalFlowScore: 80, breadthScore: 80, relativeStrengthScore: 80, riskScore: 20, status: '強勢', direction: 'up', return1d: 2, return5d: 3, return20d: 5, institutionalNetBuy: 10, tradingAmount: 100, advanceCount: 2, declineCount: 0, unchangedCount: 0, leaderStocks: [], laggardStocks: [], risks: [], tags: [], sources: [] }, { industryId: 'ship', industryName: '航運', rank: 2, previousRank: 2, rankChange: 0, strengthScore: 30, momentumScore: 30, capitalFlowScore: 30, breadthScore: 30, relativeStrengthScore: 30, riskScore: 70, status: '偏弱', direction: 'down', return1d: -2, return5d: -3, return20d: -5, institutionalNetBuy: -10, tradingAmount: 80, advanceCount: 0, declineCount: 2, unchangedCount: 0, leaderStocks: [], laggardStocks: [], risks: [], tags: [], sources: [] }], sources: [], warnings: [] })
const screener = (highRiskCount = 10): ScreenerDataset => ({ schemaVersion: '1.0', formulaVersion: 'screener-v1.0', tradeDate: '2026-07-16', generatedAt: '2026-07-16T08:00:00Z', technicalIndexGeneratedAt: '2026-07-16T08:00:00Z', sampleCount: 100, complete250Count: 90, highRiskCount, presets: [{ presetId: 'strong-trend', name: '強勢趨勢', description: '', matchedCount: 20, averageTechnicalScore: 75, averageConfidence: 80, completenessPercent: 90 }], results: [], warnings: [] })

describe('today-narrative-v1.0', () => {
  it('produces a bullish narrative from positive market data', () => expect(generateTodayMarketNarrative({ market: market(), decision: decision('bullish'), institutions: institutions(50), industries: industries(), screener: screener() }).stance).toBe('bullish'))
  it('produces a bearish narrative from negative market data', () => expect(generateTodayMarketNarrative({ market: market(-1, 250, 750), decision: decision('bearish'), institutions: institutions(-80), industries: industries(), screener: screener(60) }).stance).toBe('bearish'))
  it('keeps mixed conditions neutral', () => expect(generateTodayMarketNarrative({ market: market(0, 500, 500), decision: decision('neutral'), institutions: institutions(0), industries: industries(), screener: screener() }).stance).toBe('neutral'))
  it('returns insufficient when core sources are missing', () => expect(generateTodayMarketNarrative({ market: null, decision: null, institutions: null, industries: null, screener: null }).stance).toBe('insufficient'))
  it('is deterministic for identical input', () => { const input = { market: market(), decision: decision('bullish'), institutions: institutions(20), industries: industries(), screener: screener() }; expect(generateTodayMarketNarrative(input)).toEqual(generateTodayMarketNarrative(input)) })
  it('does not invent an industry when industry data is missing', () => expect(generateTodayMarketNarrative({ market: market(), decision: decision('neutral'), institutions: institutions(0), industries: null, screener: screener() }).summary).not.toContain('半導體'))
  it('does not claim institutional direction when data is missing', () => expect(generateTodayMarketNarrative({ market: market(), decision: decision('neutral'), institutions: null, industries: industries(), screener: screener() }).summary).not.toContain('外資買超'))
  it('exposes the fixed formula version', () => expect(generateTodayMarketNarrative({ market: market(), decision: decision('neutral'), institutions: institutions(0), industries: null, screener: null }).formulaVersion).toBe('today-narrative-v1.0'))
  it('adds a high-risk note from actual screener distribution', () => expect(generateTodayMarketNarrative({ market: market(), decision: decision('neutral'), institutions: institutions(0), industries: null, screener: screener(60) }).riskNotes.join(' ')).toContain('高風險'))
  it('reduces confidence for inconsistent trade dates', () => { const shifted = { ...industries(), tradeDate: '2026-07-14' }; const aligned = generateTodayMarketNarrative({ market: market(), decision: decision('neutral'), institutions: institutions(0), industries: industries(), screener: screener() }); const mismatched = generateTodayMarketNarrative({ market: market(), decision: decision('neutral'), institutions: institutions(0), industries: shifted, screener: screener() }); expect(mismatched.confidence).toBeLessThan(aligned.confidence) })
  it('uses observation and risk language instead of trading instructions', () => expect(getOperationEnvironment('bullish').join(' ')).not.toMatch(/買進|賣出|必漲|保證獲利/))
})
