import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

const source = (file: string) => readFile(file, 'utf8')
describe('GULI v1.1.1 history architecture contract', () => {
  it('exposes the bounded backfill script', async () => expect(await source('package.json')).toContain('"data:history:backfill"'))
  it('exposes the history validator script', async () => expect(await source('package.json')).toContain('"data:history:validate"'))
  it('exposes the technical rebuild script', async () => expect(await source('package.json')).toContain('"data:technical:rebuild"'))
  it('exposes the daily incremental script', async () => expect(await source('package.json')).toContain('"data:update-daily"'))
  it('uses only the official TWSE STOCK_DAY endpoint', async () => expect(await source('scripts/data/history/TwseHistoryFetcher.ts')).toContain('www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY'))
  it('supports a single symbol', async () => expect(await source('scripts/data/fetchTwseHistory.ts')).toContain("optionValue(argv, '--symbol')"))
  it('supports a symbol list', async () => expect(await source('scripts/data/fetchTwseHistory.ts')).toContain("optionValue(argv, '--symbols')"))
  it('supports a starting month', async () => expect(await source('scripts/data/fetchTwseHistory.ts')).toContain("optionValue(argv, '--start-month')"))
  it('supports dry run', async () => expect(await source('scripts/data/fetchTwseHistory.ts')).toContain("argv.includes('--dry-run')"))
  it('supports force refresh', async () => expect(await source('scripts/data/fetchTwseHistory.ts')).toContain("argv.includes('--force-refresh')"))
  it('uses history-progress-v1', async () => expect(await source('scripts/data/history/types.ts')).toContain("version: 'history-progress-v1'"))
  it('tracks complete, partial, failed, pending and unsupported', async () => { const text = await source('scripts/data/history/types.ts'); for (const value of ['complete', 'partial', 'failed', 'pending', 'unsupported']) expect(text).toContain(value) })
  it('keeps the existing per-stock storage root', async () => expect(await source('scripts/data/history/types.ts')).toContain("storageRoot: 'data/twse-stock-history/stocks'"))
  it('uses atomic JSON rename', async () => expect(await source('scripts/data/history/HistoryManifestWriter.ts')).toContain('rename(temporary, file)'))
  it('uses the required retry categories', async () => { const text = await source('scripts/data/history/types.ts'); for (const value of ['RATE_LIMIT', 'NETWORK_ERROR', 'INVALID_RESPONSE', 'NO_DATA', 'PARSE_ERROR', 'VALIDATION_ERROR', 'UNKNOWN']) expect(text).toContain(value) })
  it('uses 5, 15 and 45 second retry delays', async () => expect(await source('scripts/data/history/HistoryRetryQueue.ts')).toContain('[5_000, 15_000, 45_000]'))
  it('does not use Math.random in the history pipeline', async () => expect(await source('scripts/data/history/HistoryBatchRunner.ts')).not.toContain('Math.random'))
  it('keeps technical-v1.0 weights', async () => expect(await source('scripts/generate-technical-index.mjs')).toContain('trend: 0.30, momentum: 0.20, volume: 0.15, macd: 0.15, position: 0.10, risk: 0.10'))
  it('exposes EMA and support resistance without changing weights', async () => { const text = await source('scripts/generate-technical-index.mjs'); for (const value of ['ema12', 'ema26', 'support', 'resistance']) expect(text).toContain(value) })
  it('routes the manifest through the stock history repository', async () => expect(await source('src/repositories/StockHistoryRepository.ts')).toContain('getManifest()'))
  it('uses BASE_URL in the provider', async () => expect(await source('src/providers/TWSEStockHistoryProvider.ts')).toContain('import.meta.env.BASE_URL'))
  it('Settings reads progress through RepositoryHub', async () => expect(await source('src/pages/Settings.tsx')).toContain('repositoryHub.stockHistory.getManifest()'))
  it('backfill workflow is manual and bounded', async () => { const text = await source('.github/workflows/twse-history-backfill.yml'); expect(text).toContain('workflow_dispatch:'); expect(text).toContain("default: '50'"); expect(text).not.toContain('push:') })
  it('daily workflow incrementally updates existing histories', async () => expect(await source('.github/workflows/twse-daily-update.yml')).toContain('--incremental --limit=1082'))
  it('keeps GitHub Pages base and basename', async () => { expect(await source('vite.config.ts')).toContain("base: '/guli/'"); expect(await source('src/main.tsx')).toContain('basename="/guli"') })
})
